# Generated by Django 6.1.1 on 2026-09-30 23:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TentativaDeAcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "escopo",
                    models.CharField(
                        choices=[
                            ("login_usuario", "Login, por usuário digitado"),
                            ("login_ip", "Login, por endereço IP"),
                            ("cadastro_ip", "Cadastro de escritório, por endereço IP"),
                        ],
                        max_length=20,
                    ),
                ),
                ("chave", models.CharField(max_length=64)),
                (
                    "registrado_em",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["escopo", "chave", "registrado_em"],
                        name="tentativa_limite_idx",
                    ),
                    models.Index(fields=["registrado_em"], name="tentativa_venc_idx"),
                ],
            },
        ),
    ]
