"""Rotas da API de escrituração das NFS-e prestadas (DL-072, frente A).

Montadas em `config/urls.py` sob `fiscal/api/`. Todas exigem escritório ativo
e papel autorizado; o detalhe de cada permissão está em `apps.fiscal.api`.
"""

from django.urls import path

from apps.fiscal.api import (
    AliquotaIssDetalheView,
    AliquotasIssView,
    ApuracaoIssView,
    AtividadeDetalheView,
    AtividadesView,
    CadastrarAliquotaIssView,
    CadastrarAtividadeView,
    CadastrarRegimeIssView,
    ConferenciaView,
    ConfirmarFolhaView,
    ConfirmarMesView,
    ConfirmarReceitaInformadaView,
    DataPagamentoLimparTomadaView,
    DataPagamentoTomadaView,
    EfetivarNotaPrestadaView,
    EfetivarTomadaView,
    EstornarEscrituracaoView,
    EstornarFolhaView,
    EstornarReceitaInformadaView,
    EstornarTomadaView,
    FolhasFatorRView,
    IssRetidoTomadoView,
    LancarFolhaView,
    NotasPrestadasView,
    NotasTomadasView,
    OutrosMunicipiosIssView,
    PreDasView,
    RascunhoTomadaView,
    Rbt12View,
    ReabrirMesView,
    ReceitaDoMesView,
    ReceitasInformadasView,
    RegimeCaixaView,
    RegimeIssDetalheView,
    RegimesIssView,
    RegrasIssMunicipioView,
    RetencoesFederaisTomadoView,
    RetidoSofridoIssView,
)
from apps.fiscal.api_escrituracao_nfe import (
    ConferenciaNFeView,
    ConfirmarLoteNFeView,
    DefinirMarcaMonofasicoView,
    DefinirNaturezasView,
    DefinirSegmentoDevolucaoView,
    EfetivarEscrituracaoNFeView,
    EscrituracaoNFeDetalheView,
    EscrituracaoNFeListaView,
    EstornarEscrituracaoNFeView,
    LerLoteNFeView,
    PreviaLoteNFeView,
    ReclassificarNFeView,
)
from apps.fiscal.api_nfe import DetalheNFeView, NotasNFeView
from apps.fiscal.api_presumido import (
    ApuracaoPresumidoView,
    AtividadesPresumidoView,
    CriterioPresumidoView,
    DeclaracaoIntegraisPresumidoView,
    EncerrarAtividadePresumidoView,
    EncerrarMedidaPresumidoView,
    EstornarReceitaPresumidoView,
    LimitePresumidoView,
    MedidasPresumidoView,
    ParametrosPresumidoView,
    PendenciasPresumidoView,
    ReceitasPresumidoView,
    RetencoesPresumidoView,
    RevogarMedidaPresumidoView,
)

app_name = "fiscal_api"

urlpatterns = [
    # DL-080 (frente A): NF-e e NFC-e recebidas, leitura (GET). Tabelas próprias, nunca a NFS-e.
    path(
        "empresas/<int:empresa_id>/nfe/",
        NotasNFeView.as_view(),
        name="nfe_notas",
    ),
    path(
        "empresas/<int:empresa_id>/nfe/<int:documento_id>/",
        DetalheNFeView.as_view(),
        name="nfe_detalhe",
    ),
    # DL-081 (frente A): escrituração das NF-e de saída e da devolução de venda.
    # Leitura: quem consulta documentos fiscais (não CLIENTE). Escrita: quem escritura.
    path(
        "empresas/<int:empresa_id>/nfe/escrituracao/",
        EscrituracaoNFeListaView.as_view(),
        name="nfe_escrituracao_lista",
    ),
    path(
        "empresas/<int:empresa_id>/nfe/escrituracao/reclassificar/",
        ReclassificarNFeView.as_view(),
        name="nfe_escrituracao_reclassificar",
    ),
    path(
        "empresas/<int:empresa_id>/nfe/escrituracao/<int:escrituracao_id>/",
        EscrituracaoNFeDetalheView.as_view(),
        name="nfe_escrituracao_detalhe",
    ),
    path(
        "empresas/<int:empresa_id>/nfe/escrituracao/<int:escrituracao_id>/naturezas/",
        DefinirNaturezasView.as_view(),
        name="nfe_escrituracao_naturezas",
    ),
    path(
        "empresas/<int:empresa_id>/nfe/escrituracao/<int:escrituracao_id>/marca-monofasico/",
        DefinirMarcaMonofasicoView.as_view(),
        name="nfe_escrituracao_marca_monofasico",
    ),
    path(
        "empresas/<int:empresa_id>/nfe/escrituracao/<int:escrituracao_id>/segmento-devolucao/",
        DefinirSegmentoDevolucaoView.as_view(),
        name="nfe_escrituracao_segmento_devolucao",
    ),
    path(
        "empresas/<int:empresa_id>/nfe/escrituracao/<int:escrituracao_id>/efetivar/",
        EfetivarEscrituracaoNFeView.as_view(),
        name="nfe_escrituracao_efetivar",
    ),
    path(
        "empresas/<int:empresa_id>/nfe/escrituracao/<int:escrituracao_id>/estornar/",
        EstornarEscrituracaoNFeView.as_view(),
        name="nfe_escrituracao_estornar",
    ),
    path(
        "empresas/<int:empresa_id>/nfe/conferencia/",
        ConferenciaNFeView.as_view(),
        name="nfe_conferencia",
    ),
    # DL-085 (frente A): prévia do mês em lote (leitura) e confirmação em bloco (escrita).
    path(
        "empresas/<int:empresa_id>/nfe/escrituracao/lote/previa/",
        PreviaLoteNFeView.as_view(),
        name="nfe_lote_previa",
    ),
    path(
        "empresas/<int:empresa_id>/nfe/escrituracao/lote/confirmar/",
        ConfirmarLoteNFeView.as_view(),
        name="nfe_lote_confirmar",
    ),
    path(
        "empresas/<int:empresa_id>/nfe/escrituracao/lote/ler/",
        LerLoteNFeView.as_view(),
        name="nfe_lote_ler",
    ),
    path(
        "empresas/<int:empresa_id>/notas-prestadas/",
        NotasPrestadasView.as_view(),
        name="notas_prestadas",
    ),
    path(
        "empresas/<int:empresa_id>/notas-prestadas/<int:vinculo_id>/efetivar/",
        EfetivarNotaPrestadaView.as_view(),
        name="efetivar",
    ),
    path(
        "empresas/<int:empresa_id>/escrituracoes/<int:escrituracao_id>/estornar/",
        EstornarEscrituracaoView.as_view(),
        name="estornar",
    ),
    path(
        "empresas/<int:empresa_id>/conferencia/",
        ConferenciaView.as_view(),
        name="conferencia",
    ),
    # DL-078 (frente A): NFS-e TOMADAS. Escrituração própria, ISS retido e retenções federais.
    path(
        "empresas/<int:empresa_id>/tomadas/",
        NotasTomadasView.as_view(),
        name="notas_tomadas",
    ),
    path(
        "empresas/<int:empresa_id>/tomadas/<int:vinculo_id>/rascunho/",
        RascunhoTomadaView.as_view(),
        name="tomada_rascunho",
    ),
    path(
        "empresas/<int:empresa_id>/tomadas/<int:vinculo_id>/efetivar/",
        EfetivarTomadaView.as_view(),
        name="tomada_efetivar",
    ),
    path(
        "empresas/<int:empresa_id>/tomadas/escrituracoes/<int:escrituracao_id>/estornar/",
        EstornarTomadaView.as_view(),
        name="tomada_estornar",
    ),
    path(
        "empresas/<int:empresa_id>/tomadas/escrituracoes/<int:escrituracao_id>/data-pagamento/",
        DataPagamentoTomadaView.as_view(),
        name="tomada_data_pagamento",
    ),
    path(
        "empresas/<int:empresa_id>/tomadas/escrituracoes/<int:escrituracao_id>/data-pagamento/limpar/",
        DataPagamentoLimparTomadaView.as_view(),
        name="tomada_data_pagamento_limpar",
    ),
    path(
        "empresas/<int:empresa_id>/tomadas/iss-retido/",
        IssRetidoTomadoView.as_view(),
        name="tomadas_iss_retido",
    ),
    path(
        "empresas/<int:empresa_id>/tomadas/retencoes-federais/",
        RetencoesFederaisTomadoView.as_view(),
        name="tomadas_retencoes_federais",
    ),
    # DL-074 (frente A): receita mensal, confirmação, receita informada, RBT12.
    path(
        "empresas/<int:empresa_id>/receita/",
        ReceitaDoMesView.as_view(),
        name="receita_do_mes",
    ),
    path(
        "empresas/<int:empresa_id>/receita/confirmar/",
        ConfirmarMesView.as_view(),
        name="confirmar_mes",
    ),
    path(
        "empresas/<int:empresa_id>/receita/reabrir/",
        ReabrirMesView.as_view(),
        name="reabrir_mes",
    ),
    path(
        "empresas/<int:empresa_id>/receitas-informadas/",
        ReceitasInformadasView.as_view(),
        name="receitas_informadas",
    ),
    path(
        "empresas/<int:empresa_id>/receitas-informadas/<int:receita_id>/confirmar/",
        ConfirmarReceitaInformadaView.as_view(),
        name="confirmar_receita_informada",
    ),
    path(
        "empresas/<int:empresa_id>/receitas-informadas/<int:receita_id>/estornar/",
        EstornarReceitaInformadaView.as_view(),
        name="estornar_receita_informada",
    ),
    path(
        "empresas/<int:empresa_id>/rbt12/",
        Rbt12View.as_view(),
        name="rbt12",
    ),
    path(
        "empresas/<int:empresa_id>/regime-caixa/",
        RegimeCaixaView.as_view(),
        name="regime_caixa",
    ),
    # DL-075 (frente A): pré-DAS, atividades da empresa e folha para o fator r.
    path(
        "empresas/<int:empresa_id>/pre-das/",
        PreDasView.as_view(),
        name="pre_das",
    ),
    path(
        "empresas/<int:empresa_id>/atividades/",
        AtividadesView.as_view(),
        name="atividades",
    ),
    path(
        "empresas/<int:empresa_id>/atividades/nova/",
        CadastrarAtividadeView.as_view(),
        name="cadastrar_atividade",
    ),
    path(
        "empresas/<int:empresa_id>/atividades/<int:atividade_id>/",
        AtividadeDetalheView.as_view(),
        name="atividade",
    ),
    path(
        "empresas/<int:empresa_id>/folhas-fator-r/",
        FolhasFatorRView.as_view(),
        name="folhas_fator_r",
    ),
    path(
        "empresas/<int:empresa_id>/folhas-fator-r/nova/",
        LancarFolhaView.as_view(),
        name="lancar_folha",
    ),
    path(
        "empresas/<int:empresa_id>/folhas-fator-r/<int:folha_id>/confirmar/",
        ConfirmarFolhaView.as_view(),
        name="confirmar_folha",
    ),
    path(
        "empresas/<int:empresa_id>/folhas-fator-r/<int:folha_id>/estornar/",
        EstornarFolhaView.as_view(),
        name="estornar_folha",
    ),
    # DL-076 (frente A): ISS por município. Alíquota é do escritório ativo; regime e
    # apurações são por empresa.
    path(
        "iss/aliquotas/",
        AliquotasIssView.as_view(),
        name="aliquotas_iss",
    ),
    path(
        "iss/aliquotas/nova/",
        CadastrarAliquotaIssView.as_view(),
        name="cadastrar_aliquota_iss",
    ),
    path(
        "iss/aliquotas/<int:aliquota_id>/",
        AliquotaIssDetalheView.as_view(),
        name="aliquota_iss",
    ),
    path(
        "iss/regras-municipio/",
        RegrasIssMunicipioView.as_view(),
        name="regras_iss_municipio",
    ),
    path(
        "empresas/<int:empresa_id>/iss/regimes/",
        RegimesIssView.as_view(),
        name="regimes_iss",
    ),
    path(
        "empresas/<int:empresa_id>/iss/regimes/nova/",
        CadastrarRegimeIssView.as_view(),
        name="cadastrar_regime_iss",
    ),
    path(
        "empresas/<int:empresa_id>/iss/regimes/<int:regime_id>/",
        RegimeIssDetalheView.as_view(),
        name="regime_iss",
    ),
    path(
        "empresas/<int:empresa_id>/iss/apuracao/",
        ApuracaoIssView.as_view(),
        name="apuracao_iss",
    ),
    path(
        "empresas/<int:empresa_id>/iss/retido-sofrido/",
        RetidoSofridoIssView.as_view(),
        name="retido_sofrido_iss",
    ),
    path(
        "empresas/<int:empresa_id>/iss/outros-municipios/",
        OutrosMunicipiosIssView.as_view(),
        name="outros_municipios_iss",
    ),
    # DL-079 (frente A): Lucro Presumido, IRPJ e CSLL trimestrais com o acréscimo da LC 224.
    path(
        "empresas/<int:empresa_id>/presumido/atividades/",
        AtividadesPresumidoView.as_view(),
        name="presumido_atividades",
    ),
    path(
        "empresas/<int:empresa_id>/presumido/atividades/<int:atividade_id>/encerrar/",
        EncerrarAtividadePresumidoView.as_view(),
        name="presumido_encerrar_atividade",
    ),
    path(
        "empresas/<int:empresa_id>/presumido/criterio/",
        CriterioPresumidoView.as_view(),
        name="presumido_criterio",
    ),
    path(
        "empresas/<int:empresa_id>/presumido/receitas/",
        ReceitasPresumidoView.as_view(),
        name="presumido_receitas",
    ),
    path(
        "empresas/<int:empresa_id>/presumido/receitas/<int:receita_id>/estornar/",
        EstornarReceitaPresumidoView.as_view(),
        name="presumido_estornar_receita",
    ),
    path(
        "empresas/<int:empresa_id>/presumido/integrais/",
        DeclaracaoIntegraisPresumidoView.as_view(),
        name="presumido_integrais",
    ),
    path(
        "empresas/<int:empresa_id>/presumido/retencoes/",
        RetencoesPresumidoView.as_view(),
        name="presumido_retencoes",
    ),
    path(
        "empresas/<int:empresa_id>/presumido/medidas/",
        MedidasPresumidoView.as_view(),
        name="presumido_medidas",
    ),
    path(
        "empresas/<int:empresa_id>/presumido/medidas/<int:medida_id>/revogar/",
        RevogarMedidaPresumidoView.as_view(),
        name="presumido_revogar_medida",
    ),
    path(
        "empresas/<int:empresa_id>/presumido/medidas/<int:medida_id>/encerrar/",
        EncerrarMedidaPresumidoView.as_view(),
        name="presumido_encerrar_medida",
    ),
    path(
        "empresas/<int:empresa_id>/presumido/parametros/",
        ParametrosPresumidoView.as_view(),
        name="presumido_parametros",
    ),
    path(
        "empresas/<int:empresa_id>/presumido/pendencias/",
        PendenciasPresumidoView.as_view(),
        name="presumido_pendencias",
    ),
    path(
        "empresas/<int:empresa_id>/presumido/apuracao/",
        ApuracaoPresumidoView.as_view(),
        name="presumido_apuracao",
    ),
    path(
        "empresas/<int:empresa_id>/presumido/limite/",
        LimitePresumidoView.as_view(),
        name="presumido_limite",
    ),
]
