# Generated by Django 6.1.1 on 2026-09-11 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'escritório',
                'verbose_name_plural': 'escritórios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='VinculoUsuarioEscritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('administrador', 'Administrador'), ('gestor', 'Gestor'), ('analista', 'Analista'), ('financeiro', 'Financeiro'), ('paralegal', 'Paralegal'), ('cliente', 'Cliente')], max_length=20, verbose_name='papel')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='tenancy.escritorio', verbose_name='escritório')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'vínculo usuário-escritório',
                'verbose_name_plural': 'vínculos usuário-escritório',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'escritorio'), name='unico_vinculo_usuario_escritorio')],
            },
        ),
    ]
