# Generated by Django 6.1.1 on 2026-09-16 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteEscritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail do convidado')),
                ('papel_inicial', models.CharField(choices=[('administrador', 'Administrador'), ('gestor', 'Gestor'), ('analista', 'Analista'), ('financeiro', 'Financeiro'), ('paralegal', 'Paralegal'), ('cliente', 'Cliente')], default='analista', max_length=20, verbose_name='papel inicial')),
                ('token', models.CharField(help_text='Token opaco apresentado em /convite/<token>/. Único por convite.', max_length=64, unique=True, verbose_name='token de aceite')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('consumido_em', models.DateTimeField(blank=True, null=True, verbose_name='consumido em')),
                ('consumido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convites_consumidos', to=settings.AUTH_USER_MODEL, verbose_name='consumido por')),
                ('emitido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convites_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='emitido por')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='tenancy.escritorio', verbose_name='escritório')),
            ],
            options={
                'verbose_name': 'convite escritório',
                'verbose_name_plural': 'convites escritório',
                'ordering': ['-criado_em'],
            },
        ),
    ]
