# Generated by Django 6.1.1 on 2026-09-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0002_dl018_convite_escritorio"),
    ]

    operations = [
        migrations.AddField(
            model_name="escritorio",
            name="endereco_no_timbre",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Linha única de endereço para o cabeçalho dos relatórios impressos. Opcional."
                ),
                max_length=300,
                verbose_name="endereço no timbre",
            ),
        ),
        migrations.AddField(
            model_name="escritorio",
            name="razao_social_no_timbre",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Nome do escritório como deve sair no cabeçalho dos relatórios "
                    "impressos, quando diferente do nome usado na interface. Em "
                    "branco, o relatório usa o campo 'nome'."
                ),
                max_length=200,
                verbose_name="razão social no timbre",
            ),
        ),
        migrations.AddField(
            model_name="escritorio",
            name="registro_no_timbre",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Registro profissional do escritório (ex.: número de CRC) para o "
                    "cabeçalho dos relatórios impressos. Texto livre nesta rodada — o "
                    "projeto não define máscara nem validação de formato de CRC sem "
                    "confirmação do responsável pelo produto (AGENTS.md: não inventar "
                    "leiaute oficial)."
                ),
                max_length=100,
                verbose_name="registro profissional no timbre",
            ),
        ),
    ]
