# Generated by Django 6.1.1 on 2026-09-25 19:58
#
# DL-010, fatia 1 (recepção de NFS-e nacional) — migração aditiva, sem
# alteração em tabela existente. Cria os cinco modelos de
# apps/fiscal/models.py; ver DE-074 (docs/projeto/decisoes.md) para as
# decisões que moldam este esquema. Reversão: `migrate fiscal zero` (nenhum
# dado contábil envolvido — plano da etapa, seção "Impacto, riscos e
# reversão").

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0007_bl54_cnpj_check_constraint_formato"),
        ("tenancy", "0003_escritorio_endereco_no_timbre_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("nfse_nacional", "NFS-e nacional")],
                        default="nfse_nacional",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "versao",
                    models.CharField(max_length=4, verbose_name="versão do leiaute"),
                ),
                (
                    "identificador",
                    models.CharField(max_length=53, verbose_name="identificador (Id)"),
                ),
                ("xml_original", models.BinaryField(verbose_name="XML original")),
                (
                    "sha256_arquivo",
                    models.CharField(max_length=64, verbose_name="SHA-256 do arquivo"),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=13,
                        verbose_name="número (nNFSe)",
                    ),
                ),
                (
                    "dh_emissao",
                    models.DateTimeField(verbose_name="data/hora de emissão (dhEmi)"),
                ),
                (
                    "d_competencia",
                    models.DateField(verbose_name="data de competência (dCompet)"),
                ),
                (
                    "prestador_tipo_documento",
                    models.CharField(
                        choices=[
                            ("CNPJ", "CNPJ"),
                            ("CPF", "CPF"),
                            ("NIF", "NIF (identificação fiscal estrangeira)"),
                            ("nao_informado", "Não informado (cNaoNIF)"),
                        ],
                        max_length=20,
                        verbose_name="tipo de documento do prestador",
                    ),
                ),
                (
                    "prestador_documento",
                    models.CharField(
                        max_length=40, verbose_name="documento do prestador"
                    ),
                ),
                (
                    "prestador_nome",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="nome do prestador",
                    ),
                ),
                (
                    "tomador_tipo_documento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CNPJ", "CNPJ"),
                            ("CPF", "CPF"),
                            ("NIF", "NIF (identificação fiscal estrangeira)"),
                            ("nao_informado", "Não informado (cNaoNIF)"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="tipo de documento do tomador",
                    ),
                ),
                (
                    "tomador_documento",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="documento do tomador",
                    ),
                ),
                (
                    "tomador_nome",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="nome do tomador",
                    ),
                ),
                (
                    "v_serv",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=17,
                        verbose_name="valor do serviço (vServ)",
                    ),
                ),
                (
                    "v_liq",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=17,
                        verbose_name="valor líquido (vLiq)",
                    ),
                ),
                (
                    "tp_ret_issqn",
                    models.CharField(
                        max_length=1,
                        verbose_name="tipo de retenção do ISSQN (tpRetISSQN)",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "escritorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos_fiscais",
                        to="tenancy.escritorio",
                        verbose_name="escritório",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento fiscal",
                "verbose_name_plural": "documentos fiscais",
                "ordering": ["-dh_emissao"],
            },
        ),
        migrations.CreateModel(
            name="EventoFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificador",
                    models.CharField(
                        max_length=62, verbose_name="identificador (Id) do evento"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=7, verbose_name="código do evento"),
                ),
                (
                    "chave_nfse",
                    models.CharField(
                        max_length=50,
                        verbose_name="chave da NFS-e referenciada (chNFSe)",
                    ),
                ),
                (
                    "data_evento",
                    models.DateTimeField(verbose_name="data/hora do evento (dhEvento)"),
                ),
                ("xml_original", models.BinaryField(verbose_name="XML original")),
                (
                    "sha256_arquivo",
                    models.CharField(max_length=64, verbose_name="SHA-256 do arquivo"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_fiscais",
                        to="empresas.empresa",
                        verbose_name="empresa (quando identificável)",
                    ),
                ),
                (
                    "escritorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos_fiscais",
                        to="tenancy.escritorio",
                        verbose_name="escritório",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento fiscal",
                "verbose_name_plural": "eventos fiscais",
                "ordering": ["-data_evento"],
            },
        ),
        migrations.CreateModel(
            name="LoteDeRecepcao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_arquivo",
                    models.CharField(
                        max_length=255, verbose_name="nome do arquivo enviado"
                    ),
                ),
                (
                    "sha256_arquivo",
                    models.CharField(
                        max_length=64, verbose_name="SHA-256 do arquivo enviado"
                    ),
                ),
                (
                    "tamanho_bytes",
                    models.PositiveIntegerField(
                        verbose_name="tamanho do arquivo enviado (bytes)"
                    ),
                ),
                (
                    "total_arquivos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total de arquivos no envio"
                    ),
                ),
                (
                    "total_recebidos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total recebidos"
                    ),
                ),
                (
                    "total_duplicados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total duplicados"
                    ),
                ),
                (
                    "total_recusados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total recusados"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "escritorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes_de_recepcao",
                        to="tenancy.escritorio",
                        verbose_name="escritório",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes_de_recepcao",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "lote de recepção",
                "verbose_name_plural": "lotes de recepção",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ResultadoDoArquivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caminho_no_zip",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="caminho no envio",
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("recebido", "Recebido"),
                            ("duplicado", "Duplicado"),
                            ("recusado", "Recusado"),
                        ],
                        max_length=10,
                        verbose_name="resultado",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="motivo"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resultados",
                        to="fiscal.documentofiscal",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resultados",
                        to="fiscal.eventofiscal",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="fiscal.lotederecepcao",
                    ),
                ),
            ],
            options={
                "verbose_name": "resultado de arquivo",
                "verbose_name_plural": "resultados de arquivo",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="VinculoDocumentoEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "papel",
                    models.CharField(
                        choices=[("prestador", "Prestador"), ("tomador", "Tomador")],
                        max_length=10,
                        verbose_name="papel",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos",
                        to="fiscal.documentofiscal",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vinculos_documento_fiscal",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "vínculo documento-empresa",
                "verbose_name_plural": "vínculos documento-empresa",
            },
        ),
        migrations.AddConstraint(
            model_name="documentofiscal",
            constraint=models.UniqueConstraint(
                fields=("escritorio", "identificador"),
                name="documento_fiscal_unico_por_escritorio",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventofiscal",
            constraint=models.UniqueConstraint(
                fields=("escritorio", "identificador"),
                name="evento_fiscal_unico_por_escritorio",
            ),
        ),
        migrations.AddConstraint(
            model_name="vinculodocumentoempresa",
            constraint=models.UniqueConstraint(
                fields=("documento", "empresa"), name="vinculo_documento_empresa_unico"
            ),
        ),
    ]
