# Generated by Django 6.1.2 on 2026-10-08 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# DL-072 (frente A), gatilhos de PostgreSQL da escrituração fiscal. Mesmo
# desenho da DL-052 (contabilidade, migração 0013): o Python recusa, e o
# banco recusa também o que escapa do Python — `QuerySet.update()`,
# `bulk_create()` e SQL direto.
#
# 1. `escrituracao_vinculo_prestador_da_empresa`: a linha só pode apontar
#    para um vínculo de PRESTADOR da MESMA empresa (a coluna `empresa_id` é
#    redundante com `vinculo.empresa`, e o banco confere a igualdade).
#
# 2. `escrituracao_imutavel_depois_de_efetivada`: transições permitidas, e
#    só estas — rascunho -> rascunho/efetivada; efetivada -> estornada, e
#    então SÓ as colunas do estorno mudam (estado, estornada_em,
#    estornada_por_id, motivo_estorno; a comparação é `to_jsonb`, então uma
#    coluna nova nasce imutável sem ninguém lembrar de editar o gatilho).
#    Estornada não muda mais. DELETE só de rascunho.
#
# Só PostgreSQL: em SQLite (desenvolvimento local, sem produção) vale a
# guarda do Python. Limite declarado: TRUNCATE não aciona gatilho de linha.

_SQL_FUNCAO_VINCULO = """
CREATE OR REPLACE FUNCTION fiscal_escrituracao_vinculo_prestador()
RETURNS trigger AS $$
DECLARE
    v_empresa_id fiscal_escrituracaofiscal.empresa_id%TYPE;
    v_papel fiscal_vinculodocumentoempresa.papel%TYPE;
BEGIN
    SELECT v.empresa_id, v.papel INTO v_empresa_id, v_papel
      FROM fiscal_vinculodocumentoempresa AS v
     WHERE v.id = NEW.vinculo_id;
    IF NOT FOUND OR v_empresa_id <> NEW.empresa_id OR v_papel <> 'prestador' THEN
        RAISE EXCEPTION 'escrituração exige vínculo de prestador da mesma empresa'
            USING ERRCODE = '23514',
                  CONSTRAINT = 'escrituracao_vinculo_prestador_da_empresa';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

_SQL_GATILHO_VINCULO = """
CREATE TRIGGER trg_escrituracao_vinculo_prestador
BEFORE INSERT OR UPDATE ON fiscal_escrituracaofiscal
FOR EACH ROW EXECUTE FUNCTION fiscal_escrituracao_vinculo_prestador();
"""

_SQL_FUNCAO_IMUTAVEL = """
CREATE OR REPLACE FUNCTION fiscal_escrituracao_imutavel()
RETURNS trigger AS $$
DECLARE
    colunas_do_estorno text[] := ARRAY[
        'estado', 'estornada_em', 'estornada_por_id', 'motivo_estorno'
    ];
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.estado <> 'rascunho' THEN
            RAISE EXCEPTION 'escrituração efetivada ou estornada não pode ser excluída'
                USING ERRCODE = '23514',
                      CONSTRAINT = 'escrituracao_imutavel_depois_de_efetivada';
        END IF;
        RETURN OLD;
    END IF;

    IF OLD.estado = 'rascunho' AND NEW.estado IN ('rascunho', 'efetivada') THEN
        RETURN NEW;
    END IF;

    IF OLD.estado = 'efetivada' AND NEW.estado = 'estornada' THEN
        IF (to_jsonb(NEW) - colunas_do_estorno)
           IS DISTINCT FROM (to_jsonb(OLD) - colunas_do_estorno) THEN
            RAISE EXCEPTION
                'escrituração efetivada só pode ser estornada; os dados do ato não mudam'
                USING ERRCODE = '23514',
                      CONSTRAINT = 'escrituracao_imutavel_depois_de_efetivada';
        END IF;
        RETURN NEW;
    END IF;

    IF OLD.estado = 'efetivada' AND NEW.estado = 'efetivada' THEN
        IF to_jsonb(NEW) IS DISTINCT FROM to_jsonb(OLD) THEN
            RAISE EXCEPTION 'escrituração efetivada não pode ser alterada; estorne com motivo'
                USING ERRCODE = '23514',
                      CONSTRAINT = 'escrituracao_imutavel_depois_de_efetivada';
        END IF;
        RETURN NEW;
    END IF;

    RAISE EXCEPTION
        'transição de estado da escrituração não permitida: % -> %',
        OLD.estado, NEW.estado
        USING ERRCODE = '23514',
              CONSTRAINT = 'escrituracao_imutavel_depois_de_efetivada';
END;
$$ LANGUAGE plpgsql;
"""

_SQL_GATILHO_IMUTAVEL = """
CREATE TRIGGER trg_escrituracao_imutavel
BEFORE UPDATE OR DELETE ON fiscal_escrituracaofiscal
FOR EACH ROW EXECUTE FUNCTION fiscal_escrituracao_imutavel();
"""

_SQL_DESFAZER = """
DROP TRIGGER IF EXISTS trg_escrituracao_imutavel ON fiscal_escrituracaofiscal;
DROP TRIGGER IF EXISTS trg_escrituracao_vinculo_prestador ON fiscal_escrituracaofiscal;
DROP FUNCTION IF EXISTS fiscal_escrituracao_imutavel();
DROP FUNCTION IF EXISTS fiscal_escrituracao_vinculo_prestador();
"""


def _criar_gatilhos(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for sql in (
        _SQL_FUNCAO_VINCULO,
        _SQL_GATILHO_VINCULO,
        _SQL_FUNCAO_IMUTAVEL,
        _SQL_GATILHO_IMUTAVEL,
    ):
        schema_editor.execute(sql, params=None)


def _desfazer_gatilhos(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(_SQL_DESFAZER, params=None)


class Migration(migrations.Migration):
    dependencies = [
        # 0007 e não a última (0015): a escrituração só precisa da tabela
        # `empresas_empresa` e da chave dela — o mesmo que `fiscal.0001` já exige.
        # Depender da última faz QUALQUER migração de teste que reverta `empresas`
        # para uma versão anterior (test_dl038, test_dl041, test_dl076_b8) desfazer
        # esta tabela, e ela não volta — medido: a suíte completa perdeu os
        # testes transacionais de escrituração depois de test_dl038.
        ("empresas", "0007_bl54_cnpj_check_constraint_formato"),
        ("fiscal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EscrituracaoFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "natureza",
                    models.CharField(
                        choices=[
                            (
                                "prestado_iss_devido_prestador",
                                "Serviço prestado — ISS devido pelo prestador",
                            ),
                            (
                                "prestado_iss_retido",
                                "Serviço prestado — ISS retido pelo tomador ou pelo intermediário",
                            ),
                            (
                                "prestado_iss_outro_municipio",
                                "Serviço prestado — ISS devido a outro município",
                            ),
                            (
                                "prestado_exportacao_servico",
                                "Serviço prestado — exportação de serviço (mercado externo)",
                            ),
                            (
                                "prestado_iss_imune_isento_reduzido",
                                "Serviço prestado — ISS imune, isento ou reduzido por lei do ente",
                            ),
                            (
                                "prestado_fora_lista_lc116",
                                "Serviço prestado — fora da lista da LC 116 (sem ISS)",
                            ),
                        ],
                        max_length=40,
                        verbose_name="natureza da operação",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("efetivada", "Efetivada"),
                            ("estornada", "Estornada"),
                        ],
                        default="rascunho",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                (
                    "data_emissao",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="data de emissão (dhEmi, em Brasília)",
                    ),
                ),
                (
                    "data_competencia",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="data de competência (dCompet)",
                    ),
                ),
                (
                    "valor_servico",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=17,
                        null=True,
                        verbose_name="valor do serviço",
                    ),
                ),
                (
                    "valor_liquido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=17,
                        null=True,
                        verbose_name="valor líquido",
                    ),
                ),
                (
                    "iss_retido",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="ISS retido (tpRetISSQN 2 ou 3)",
                    ),
                ),
                (
                    "efetivada_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="efetivada em"),
                ),
                (
                    "estornada_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="estornada em"),
                ),
                (
                    "motivo_estorno",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="motivo do estorno",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criada por",
                    ),
                ),
                (
                    "efetivada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="efetivada por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escrituracoes_fiscais",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "estornada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="estornada por",
                    ),
                ),
                (
                    "vinculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escrituracoes_fiscais",
                        to="fiscal.vinculodocumentoempresa",
                        verbose_name="vínculo documento-empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "escrituração fiscal",
                "verbose_name_plural": "escriturações fiscais",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("estado__in", ["rascunho", "efetivada"])),
                        fields=("vinculo",),
                        name="escrituracao_ativa_unica_por_vinculo",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("estado__in", ["rascunho", "efetivada", "estornada"])),
                        name="escrituracao_estado_valido",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("efetivada_em__isnull", True),
                                ("efetivada_por__isnull", True),
                                ("estado", "rascunho"),
                                ("estornada_em__isnull", True),
                                ("estornada_por__isnull", True),
                                ("motivo_estorno", ""),
                            ),
                            models.Q(
                                ("data_competencia__isnull", False),
                                ("data_emissao__isnull", False),
                                ("efetivada_em__isnull", False),
                                ("efetivada_por__isnull", False),
                                ("estado", "efetivada"),
                                ("estornada_em__isnull", True),
                                ("estornada_por__isnull", True),
                                ("iss_retido__isnull", False),
                                ("motivo_estorno", ""),
                                ("valor_liquido__isnull", False),
                                ("valor_servico__isnull", False),
                            ),
                            models.Q(
                                models.Q(("motivo_estorno", ""), _negated=True),
                                ("data_competencia__isnull", False),
                                ("data_emissao__isnull", False),
                                ("efetivada_em__isnull", False),
                                ("efetivada_por__isnull", False),
                                ("estado", "estornada"),
                                ("estornada_em__isnull", False),
                                ("estornada_por__isnull", False),
                                ("iss_retido__isnull", False),
                                ("valor_liquido__isnull", False),
                                ("valor_servico__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="escrituracao_campos_coerentes_com_o_estado",
                    ),
                ],
            },
        ),
        migrations.RunPython(_criar_gatilhos, _desfazer_gatilhos),
    ]
