# Generated by Django 6.1.2 on 2026-10-08 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# DL-074 (frente A), gatilhos de PostgreSQL da receita informada e da confirmação
# mensal. Mesmo desenho da migração 0002 (DL-072): o Python recusa, e o banco recusa
# também o que escapa do Python (`QuerySet.update()`, `bulk_create()`, SQL direto).
#
# 1. `receita_informada_imutavel_depois_de_confirmada`: rascunho -> rascunho/confirmada
#    (qualquer coluna); confirmada -> estornada (só as colunas do estorno);
#    confirmada -> confirmada só se nada mudou; estornada não muda mais; DELETE só
#    de rascunho.
#
# 2. `confirmacao_mes_imutavel_depois_de_confirmada`: as colunas do ATO (quem e
#    quando confirmou, e os totais confirmados) e a chave (empresa, ano, mês, criado)
#    não mudam depois de confirmada. Confirmada -> reaberta muda só o que a reabertura
#    grava. Reaberta -> confirmada (nova confirmação) grava novo ato. DELETE nunca.
#
# Só PostgreSQL: em SQLite vale a guarda do Python. Limite declarado: TRUNCATE não
# aciona gatilho de linha (mesmo limite da DL-052 e da DL-072).
#
# Limite declarado (A8, achado da auditoria DL-074 rodada 1): na transição
# reaberta -> confirmada, as colunas do total (`valor_confirmado_interno` e
# `valor_confirmado_externo`) são livres, porque a nova confirmação grava um total
# novo. Por isso um UPDATE SQL direto nessa transição pode regravar um total
# qualquer: o gatilho não confere o total com a composição do mês. Os serviços não
# fazem isso (o total vem do instante do ato). É limite como o TRUNCATE, e a defesa
# é o acesso direto ao banco, não este gatilho.

_SQL_FUNCAO_RECEITA = """
CREATE OR REPLACE FUNCTION fiscal_receita_informada_imutavel()
RETURNS trigger AS $$
DECLARE
    colunas_do_estorno text[] := ARRAY[
        'estado', 'estornada_em', 'estornada_por_id', 'motivo_estorno'
    ];
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.estado <> 'rascunho' THEN
            RAISE EXCEPTION 'receita informada confirmada ou estornada não pode ser excluída'
                USING ERRCODE = '23514',
                      CONSTRAINT = 'receita_informada_imutavel_depois_de_confirmada';
        END IF;
        RETURN OLD;
    END IF;

    IF OLD.estado = 'rascunho' AND NEW.estado IN ('rascunho', 'confirmada') THEN
        RETURN NEW;
    END IF;

    IF OLD.estado = 'confirmada' AND NEW.estado = 'estornada' THEN
        IF (to_jsonb(NEW) - colunas_do_estorno)
           IS DISTINCT FROM (to_jsonb(OLD) - colunas_do_estorno) THEN
            RAISE EXCEPTION
                'receita informada confirmada só pode ser estornada; os dados não mudam'
                USING ERRCODE = '23514',
                      CONSTRAINT = 'receita_informada_imutavel_depois_de_confirmada';
        END IF;
        RETURN NEW;
    END IF;

    IF OLD.estado = 'confirmada' AND NEW.estado = 'confirmada' THEN
        IF to_jsonb(NEW) IS DISTINCT FROM to_jsonb(OLD) THEN
            RAISE EXCEPTION 'receita informada confirmada não pode ser alterada; estorne com motivo'
                USING ERRCODE = '23514',
                      CONSTRAINT = 'receita_informada_imutavel_depois_de_confirmada';
        END IF;
        RETURN NEW;
    END IF;

    RAISE EXCEPTION
        'transição de estado da receita informada não permitida: % -> %',
        OLD.estado, NEW.estado
        USING ERRCODE = '23514',
              CONSTRAINT = 'receita_informada_imutavel_depois_de_confirmada';
END;
$$ LANGUAGE plpgsql;
"""

_SQL_GATILHO_RECEITA = """
CREATE TRIGGER trg_receita_informada_imutavel
BEFORE UPDATE OR DELETE ON fiscal_receitainformada
FOR EACH ROW EXECUTE FUNCTION fiscal_receita_informada_imutavel();
"""

_SQL_FUNCAO_CONFIRMACAO = """
CREATE OR REPLACE FUNCTION fiscal_confirmacao_mes_imutavel()
RETURNS trigger AS $$
DECLARE
    colunas_livres text[];
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'confirmação de receita mensal não pode ser excluída'
            USING ERRCODE = '23514',
                  CONSTRAINT = 'confirmacao_mes_imutavel_depois_de_confirmada';
    END IF;

    -- Regra: em cada transição, SÓ as colunas livres podem mudar; todas as outras
    -- (chave, id, criado_em e, depois de confirmada, o ato) são iguais às de antes.
    IF OLD.estado = 'confirmada' AND NEW.estado = 'confirmada' THEN
        colunas_livres := ARRAY[]::text[];
    ELSIF OLD.estado = 'confirmada' AND NEW.estado = 'reaberta' THEN
        -- Reabrir grava o motivo e quem reabriu; o ato de confirmação não muda.
        colunas_livres := ARRAY[
            'estado', 'reaberta_em', 'reaberta_por_id', 'motivo_reabertura', 'a_retificar'
        ];
    ELSIF OLD.estado = 'reaberta' AND NEW.estado = 'reaberta' THEN
        -- O estorno só marca "a retificar" num mês já reaberto.
        colunas_livres := ARRAY['a_retificar'];
    ELSIF OLD.estado = 'reaberta' AND NEW.estado = 'confirmada' THEN
        -- Nova confirmação: grava um ato novo e limpa a reabertura.
        colunas_livres := ARRAY[
            'estado', 'a_retificar', 'confirmada_em', 'confirmada_por_id',
            'valor_confirmado_interno', 'valor_confirmado_externo',
            'reaberta_em', 'reaberta_por_id', 'motivo_reabertura'
        ];
    ELSE
        RAISE EXCEPTION
            'transição da confirmação de receita mensal não permitida: % -> %',
            OLD.estado, NEW.estado
            USING ERRCODE = '23514',
                  CONSTRAINT = 'confirmacao_mes_imutavel_depois_de_confirmada';
    END IF;

    IF (to_jsonb(NEW) - colunas_livres) IS DISTINCT FROM (to_jsonb(OLD) - colunas_livres) THEN
        RAISE EXCEPTION 'confirmação de receita mensal: só o que a transição permite pode mudar'
            USING ERRCODE = '23514',
                  CONSTRAINT = 'confirmacao_mes_imutavel_depois_de_confirmada';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

_SQL_GATILHO_CONFIRMACAO = """
CREATE TRIGGER trg_confirmacao_mes_imutavel
BEFORE UPDATE OR DELETE ON fiscal_confirmacaoreceitamensal
FOR EACH ROW EXECUTE FUNCTION fiscal_confirmacao_mes_imutavel();
"""

_SQL_DESFAZER = """
DROP TRIGGER IF EXISTS trg_confirmacao_mes_imutavel ON fiscal_confirmacaoreceitamensal;
DROP TRIGGER IF EXISTS trg_receita_informada_imutavel ON fiscal_receitainformada;
DROP FUNCTION IF EXISTS fiscal_confirmacao_mes_imutavel();
DROP FUNCTION IF EXISTS fiscal_receita_informada_imutavel();
"""


def _criar_gatilhos(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for sql in (
        _SQL_FUNCAO_RECEITA,
        _SQL_GATILHO_RECEITA,
        _SQL_FUNCAO_CONFIRMACAO,
        _SQL_GATILHO_CONFIRMACAO,
    ):
        schema_editor.execute(sql, params=None)


def _desfazer_gatilhos(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(_SQL_DESFAZER, params=None)



class Migration(migrations.Migration):

    dependencies = [
        # 0007 e não a última de `empresas` (ver a mesma decisão na migração 0002, DL-072):
        # depender da última faz QUALQUER teste que reverta `empresas` desfazer esta
        # migração e não a reaplicar, e os testes seguintes perdem tabelas. Esta migração
        # só precisa de `empresas_empresa`, que existe desde 0001.
        ("empresas", "0007_bl54_cnpj_check_constraint_formato"),
        ("fiscal", "0002_dl072_escrituracao_fiscal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfirmacaoReceitaMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ano",
                    models.PositiveSmallIntegerField(verbose_name="ano da competência"),
                ),
                (
                    "mes",
                    models.PositiveSmallIntegerField(verbose_name="mês da competência"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("confirmada", "Confirmada"),
                            ("reaberta", "Reaberta"),
                        ],
                        default="confirmada",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "valor_confirmado_interno",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=17,
                        verbose_name="receita confirmada — interno",
                    ),
                ),
                (
                    "valor_confirmado_externo",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=17,
                        verbose_name="receita confirmada — externo",
                    ),
                ),
                ("confirmada_em", models.DateTimeField(verbose_name="confirmada em")),
                (
                    "a_retificar",
                    models.BooleanField(default=False, verbose_name="a retificar"),
                ),
                (
                    "reaberta_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reaberta em"
                    ),
                ),
                (
                    "motivo_reabertura",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="motivo da reabertura",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "confirmada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="confirmada por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmacoes_receita_mensal",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "reaberta_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reaberta por",
                    ),
                ),
            ],
            options={
                "verbose_name": "confirmação de receita mensal",
                "verbose_name_plural": "confirmações de receita mensal",
                "ordering": ["empresa_id", "ano", "mes"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "ano", "mes"),
                        name="confirmacao_mes_unica_por_empresa",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ano__gte", 1970),
                            ("ano__lte", 2999),
                            ("mes__gte", 1),
                            ("mes__lte", 12),
                        ),
                        name="confirmacao_mes_valido",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("estado__in", ["confirmada", "reaberta"])),
                        name="confirmacao_estado_valido",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valor_confirmado_externo__gte", 0),
                            ("valor_confirmado_interno__gte", 0),
                        ),
                        name="confirmacao_valores_nao_negativos",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("a_retificar", False),
                                ("estado", "confirmada"),
                                ("motivo_reabertura", ""),
                                ("reaberta_em__isnull", True),
                                ("reaberta_por__isnull", True),
                            ),
                            models.Q(
                                ("estado", "reaberta"),
                                ("reaberta_em__isnull", False),
                                ("reaberta_por__isnull", False),
                                models.Q(("motivo_reabertura", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="confirmacao_campos_coerentes_com_o_estado",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OpcaoRegimeCaixaSimples",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ano_calendario",
                    models.PositiveSmallIntegerField(verbose_name="ano-calendário"),
                ),
                (
                    "registrada_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="registrada em"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opcoes_regime_caixa_simples",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "registrada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "opção pelo regime de caixa (Simples)",
                "verbose_name_plural": "opções pelo regime de caixa (Simples)",
                "ordering": ["empresa_id", "ano_calendario"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "ano_calendario"),
                        name="opcao_caixa_unica_por_ano",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ano_calendario__gte", 2000), ("ano_calendario__lte", 2026)
                        ),
                        name="opcao_caixa_so_ate_2026",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReceitaInformada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ano",
                    models.PositiveSmallIntegerField(verbose_name="ano da competência"),
                ),
                (
                    "mes",
                    models.PositiveSmallIntegerField(verbose_name="mês da competência"),
                ),
                (
                    "mercado",
                    models.CharField(
                        choices=[
                            ("interno", "Mercado interno"),
                            ("externo", "Mercado externo (exportação de serviço)"),
                        ],
                        max_length=10,
                        verbose_name="mercado",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=17, verbose_name="valor da receita"
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            (
                                "historico_pre_sistema",
                                "Histórico anterior ao uso do sistema",
                            ),
                            (
                                "mercadoria_nao_escriturada",
                                "Venda de mercadoria ainda não escriturada",
                            ),
                            (
                                "servico_documento_nao_integrado",
                                "Serviço com documento de município não integrado",
                            ),
                            (
                                "outras_receitas_atividade",
                                "Outras receitas da atividade (Res. CGSN 140, art. 2º, § 4º)",
                            ),
                            ("ajuste", "Ajuste ou retificação"),
                        ],
                        max_length=40,
                        verbose_name="origem",
                    ),
                ),
                ("motivo", models.CharField(max_length=500, verbose_name="motivo")),
                (
                    "documento_suporte",
                    models.CharField(
                        max_length=300, verbose_name="documento de suporte"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("confirmada", "Confirmada"),
                            ("estornada", "Estornada"),
                        ],
                        default="rascunho",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "confirmada_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="confirmada em"
                    ),
                ),
                (
                    "estornada_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="estornada em"
                    ),
                ),
                (
                    "motivo_estorno",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="motivo do estorno",
                    ),
                ),
                (
                    "confirmada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="confirmada por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criada por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receitas_informadas",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "estornada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="estornada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "receita informada",
                "verbose_name_plural": "receitas informadas",
                "ordering": ["id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ano__gte", 1970),
                            ("ano__lte", 2999),
                            ("mes__gte", 1),
                            ("mes__lte", 12),
                        ),
                        name="receita_informada_mes_valido",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("valor__gt", 0)),
                        name="receita_informada_valor_positivo",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("estado__in", ["rascunho", "confirmada", "estornada"]),
                            ("mercado__in", ["interno", "externo"]),
                            (
                                "origem__in",
                                [
                                    "historico_pre_sistema",
                                    "mercadoria_nao_escriturada",
                                    "servico_documento_nao_integrado",
                                    "outras_receitas_atividade",
                                    "ajuste",
                                ],
                            ),
                        ),
                        name="receita_informada_catalogos_validos",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("motivo", ""), _negated=True),
                            models.Q(("documento_suporte", ""), _negated=True),
                        ),
                        name="receita_informada_campos_obrigatorios",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("confirmada_em__isnull", True),
                                ("confirmada_por__isnull", True),
                                ("estado", "rascunho"),
                                ("estornada_em__isnull", True),
                                ("estornada_por__isnull", True),
                                ("motivo_estorno", ""),
                            ),
                            models.Q(
                                ("confirmada_em__isnull", False),
                                ("confirmada_por__isnull", False),
                                ("estado", "confirmada"),
                                ("estornada_em__isnull", True),
                                ("estornada_por__isnull", True),
                                ("motivo_estorno", ""),
                            ),
                            models.Q(
                                ("confirmada_em__isnull", False),
                                ("confirmada_por__isnull", False),
                                ("estado", "estornada"),
                                ("estornada_em__isnull", False),
                                ("estornada_por__isnull", False),
                                models.Q(("motivo_estorno", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="receita_informada_campos_coerentes_com_o_estado",
                    ),
                ],
            },
        ),
        migrations.RunPython(_criar_gatilhos, _desfazer_gatilhos),
    ]
