# Generated by Django 6.1.2 on 2026-10-08 06:26
#
# DL-075 (frente A): atividades da empresa, folha para o fator r e `atividade` na receita
# informada. Migração ADITIVA: só cria tabelas e colunas novas, sem alterar dado existente.
#
# Gatilho de PostgreSQL da folha (mesmo desenho da receita informada, migração 0003):
# `fiscal_folha_fator_r_imutavel`. Rascunho muda livre; confirmada só vai a estornada,
# e só as colunas do estorno mudam; estornada não muda mais; DELETE só de rascunho.
# Só PostgreSQL: em SQLite vale a guarda do Python (`FolhaFatorR.save/delete`).
# Limite declarado: TRUNCATE não aciona gatilho de linha (mesmo limite da DL-052).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

_SQL_FUNCAO_FOLHA = """
CREATE OR REPLACE FUNCTION fiscal_folha_fator_r_imutavel()
RETURNS trigger AS $$
DECLARE
    colunas_do_estorno text[] := ARRAY[
        'estado', 'estornada_em', 'estornada_por_id', 'motivo_estorno'
    ];
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.estado <> 'rascunho' THEN
            RAISE EXCEPTION 'folha confirmada ou estornada não pode ser excluída'
                USING ERRCODE = '23514',
                      CONSTRAINT = 'folha_imutavel_depois_de_confirmada';
        END IF;
        RETURN OLD;
    END IF;

    IF OLD.estado = 'rascunho' AND NEW.estado IN ('rascunho', 'confirmada') THEN
        RETURN NEW;
    END IF;

    IF OLD.estado = 'confirmada' AND NEW.estado = 'estornada' THEN
        IF (to_jsonb(NEW) - colunas_do_estorno)
           IS DISTINCT FROM (to_jsonb(OLD) - colunas_do_estorno) THEN
            RAISE EXCEPTION 'folha confirmada só pode ser estornada; os dados não mudam'
                USING ERRCODE = '23514',
                      CONSTRAINT = 'folha_imutavel_depois_de_confirmada';
        END IF;
        RETURN NEW;
    END IF;

    RAISE EXCEPTION
        'transição de estado da folha não permitida: % -> %', OLD.estado, NEW.estado
        USING ERRCODE = '23514',
              CONSTRAINT = 'folha_imutavel_depois_de_confirmada';
END;
$$ LANGUAGE plpgsql;
"""

_SQL_GATILHO_FOLHA = """
CREATE TRIGGER trg_folha_fator_r_imutavel
BEFORE UPDATE OR DELETE ON fiscal_folhafatorr
FOR EACH ROW EXECUTE FUNCTION fiscal_folha_fator_r_imutavel();
"""

_SQL_DESFAZER_FOLHA = """
DROP TRIGGER IF EXISTS trg_folha_fator_r_imutavel ON fiscal_folhafatorr;
DROP FUNCTION IF EXISTS fiscal_folha_fator_r_imutavel();
"""


def _criar_gatilho_folha(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(_SQL_FUNCAO_FOLHA, params=None)
    schema_editor.execute(_SQL_GATILHO_FOLHA, params=None)


def _desfazer_gatilho_folha(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(_SQL_DESFAZER_FOLHA, params=None)


class Migration(migrations.Migration):
    dependencies = [
        # 0007 e não a última de `empresas`, pela mesma razão da migração 0003 (DL-074):
        # há testes que revertem `empresas` para 0007..0011. Depender da última (0016)
        # faria esses testes desfazerem ESTA migração e não a reaplicarem, e os testes
        # seguintes perderiam as colunas novas. Esta migração só precisa de
        # `empresas_empresa`, que existe desde 0001.
        ("empresas", "0007_bl54_cnpj_check_constraint_formato"),
        ("fiscal", "0003_dl074_receita_e_confirmacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AtividadeEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="descrição da atividade"),
                ),
                (
                    "codigo_subitem",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="código do subitem (LC 116 / cTribNac), informativo",
                    ),
                ),
                (
                    "enquadramento",
                    models.CharField(
                        choices=[
                            ("anexo_iii", "Anexo III (sem fator r)"),
                            ("anexo_iii_ou_v_fator_r", "Anexo III ou V, pelo fator r"),
                            ("anexo_iv", "Anexo IV (CPP fora do DAS)"),
                        ],
                        max_length=32,
                        verbose_name="enquadramento",
                    ),
                ),
                ("inicio", models.DateField(verbose_name="início da vigência")),
                (
                    "fim",
                    models.DateField(blank=True, null=True, verbose_name="fim da vigência"),
                ),
                (
                    "padrao",
                    models.BooleanField(default=False, verbose_name="atividade padrão da empresa"),
                ),
                (
                    "criada_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "criada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criada por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atividades_fiscais",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "atividade da empresa (Simples)",
                "verbose_name_plural": "atividades da empresa (Simples)",
                "ordering": ["empresa_id", "inicio", "id"],
            },
        ),
        migrations.AddField(
            model_name="receitainformada",
            name="atividade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receitas_informadas",
                to="fiscal.atividadeempresa",
                verbose_name="atividade",
            ),
        ),
        migrations.CreateModel(
            name="FolhaFatorR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ano",
                    models.PositiveSmallIntegerField(verbose_name="ano da competência"),
                ),
                (
                    "mes",
                    models.PositiveSmallIntegerField(verbose_name="mês da competência"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("confirmada", "Confirmada"),
                            ("estornada", "Estornada"),
                        ],
                        default="rascunho",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                (
                    "remuneracao_empregados_avulsos",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=17,
                        verbose_name="remuneração base INSS — empregados e avulsos",
                    ),
                ),
                (
                    "pro_labore_autonomos",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=17,
                        verbose_name="pró-labore e autônomos",
                    ),
                ),
                (
                    "decimo_terceiro",
                    models.DecimalField(
                        decimal_places=2, max_digits=17, verbose_name="13º salário"
                    ),
                ),
                (
                    "cpp_recolhida",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=17,
                        verbose_name="CPP recolhida (inclusive a do DAS)",
                    ),
                ),
                (
                    "fgts_recolhido",
                    models.DecimalField(
                        decimal_places=2, max_digits=17, verbose_name="FGTS recolhido"
                    ),
                ),
                (
                    "documento_suporte",
                    models.CharField(max_length=300, verbose_name="documento de suporte"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "confirmada_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="confirmada em"),
                ),
                (
                    "estornada_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="estornada em"),
                ),
                (
                    "motivo_estorno",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="motivo do estorno",
                    ),
                ),
                (
                    "confirmada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="confirmada por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criada por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="folhas_fator_r",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "estornada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="estornada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "folha mensal para o fator r",
                "verbose_name_plural": "folhas mensais para o fator r",
                "ordering": ["empresa_id", "ano", "mes", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="atividadeempresa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fim__isnull", True),
                    ("fim__gte", models.F("inicio")),
                    _connector="OR",
                ),
                name="atividade_fim_depois_do_inicio",
            ),
        ),
        migrations.AddConstraint(
            model_name="atividadeempresa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "enquadramento__in",
                        ["anexo_iii", "anexo_iii_ou_v_fator_r", "anexo_iv"],
                    )
                ),
                name="atividade_enquadramento_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="atividadeempresa",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fim__isnull", True), ("padrao", True)),
                fields=("empresa",),
                name="atividade_padrao_unica_em_aberto",
            ),
        ),
        migrations.AddConstraint(
            model_name="folhafatorr",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ano__gte", 1970),
                    ("ano__lte", 2999),
                    ("mes__gte", 1),
                    ("mes__lte", 12),
                ),
                name="folha_mes_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="folhafatorr",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("remuneracao_empregados_avulsos__gte", 0),
                    ("pro_labore_autonomos__gte", 0),
                    ("decimo_terceiro__gte", 0),
                    ("cpp_recolhida__gte", 0),
                    ("fgts_recolhido__gte", 0),
                ),
                name="folha_valores_nao_negativos",
            ),
        ),
        migrations.AddConstraint(
            model_name="folhafatorr",
            constraint=models.CheckConstraint(
                condition=models.Q(("documento_suporte", ""), _negated=True),
                name="folha_campos_obrigatorios",
            ),
        ),
        migrations.AddConstraint(
            model_name="folhafatorr",
            constraint=models.CheckConstraint(
                condition=models.Q(("estado__in", ["rascunho", "confirmada", "estornada"])),
                name="folha_estado_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="folhafatorr",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("confirmada_em__isnull", True),
                        ("confirmada_por__isnull", True),
                        ("estado", "rascunho"),
                        ("estornada_em__isnull", True),
                        ("estornada_por__isnull", True),
                        ("motivo_estorno", ""),
                    ),
                    models.Q(
                        ("confirmada_em__isnull", False),
                        ("confirmada_por__isnull", False),
                        ("estado", "confirmada"),
                        ("estornada_em__isnull", True),
                        ("estornada_por__isnull", True),
                        ("motivo_estorno", ""),
                    ),
                    models.Q(
                        ("confirmada_em__isnull", False),
                        ("confirmada_por__isnull", False),
                        ("estado", "estornada"),
                        ("estornada_em__isnull", False),
                        ("estornada_por__isnull", False),
                        models.Q(("motivo_estorno", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="folha_campos_coerentes_com_o_estado",
            ),
        ),
        migrations.AddConstraint(
            model_name="folhafatorr",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "estornada"), _negated=True),
                fields=("empresa", "ano", "mes"),
                name="folha_mes_unica_ativa_por_empresa",
            ),
        ),
        migrations.RunPython(_criar_gatilho_folha, _desfazer_gatilho_folha),
    ]
