# Generated by Django 6.1.2 on 2026-10-08 08:18

# DL-075 (HI-80): situação do ISS na receita informada. Migração ADITIVA: a coluna é
# `null=True` e nenhuma linha antiga é reescrita. Por isso a regra "interno exige
# situação" NÃO é de banco (linhas antigas do interno ficariam inválidas): o serviço
# recusa, e o pré-DAS bloqueia as receitas confirmadas sem situação, nomeando cada uma.
#
# Imutabilidade (gatilho da migração 0003): não precisa de mudança. A função
# `fiscal_receita_informada_imutavel()` compara a linha INTEIRA (`to_jsonb(NEW)` contra
# `to_jsonb(OLD)`) em confirmada -> confirmada, e em confirmada -> estornada só libera as
# colunas do estorno. A coluna nova fica protegida como as demais.
#
# As duas restrições novas (catálogo válido, e "fora do interno não há situação") são
# inventariadas em `apps/core/restricoes.py`.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        # 0007 e não a última de `empresas`, pela mesma razão da migração 0003 (DL-074):
        # há testes que revertem `empresas` para 0007..0011. Depender da última (0016)
        # faria esses testes desfazerem ESTA migração e não a reaplicarem, e os testes
        # seguintes perderiam a coluna `situacao_iss`. Esta migração só altera
        # `fiscal_receitainformada`, que já existe desde a migração 0003.
        ("empresas", "0007_bl54_cnpj_check_constraint_formato"),
        ("fiscal", "0004_dl075_pre_das_atividades_e_folha"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="receitainformada",
            name="situacao_iss",
            field=models.CharField(
                blank=True,
                choices=[
                    ("proprio_municipio", "ISS devido ao próprio município"),
                    ("outro_municipio", "ISS devido a outro município"),
                    ("retido", "ISS retido ou substituído pelo tomador"),
                ],
                max_length=20,
                null=True,
                verbose_name="situação do ISS",
            ),
        ),
        migrations.AddConstraint(
            model_name="receitainformada",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("situacao_iss__isnull", True),
                    (
                        "situacao_iss__in",
                        ["proprio_municipio", "outro_municipio", "retido"],
                    ),
                    _connector="OR",
                ),
                name="receita_informada_situacao_iss_valida",
            ),
        ),
        migrations.AddConstraint(
            model_name="receitainformada",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("mercado", "interno"),
                    ("situacao_iss__isnull", True),
                    _connector="OR",
                ),
                name="receita_informada_iss_so_no_interno",
            ),
        ),
    ]
