# Generated by Django 6.1.2 on 2026-10-08 09:24

# DL-076 (frente A): ISS por município. Migração ADITIVA: três tabelas novas, e nenhuma
# linha existente é alterada. A semeadura de Palmas é DADO LEGAL COMUM (HI-83): a regra é
# a mesma para todos os escritórios, por isso a linha é global (sem escritório) e não tem
# autor humano (`criada_por` nulo). A reversão remove só essa linha.
#
# Fonte da regra: Decreto 1.667/2018 (RCTM de Palmas), art. 86 § 3º e Anexo I, cópia
# íntegra em legisweb, consultada em 08/10/2026 (consulta do contador-senior, item 2).
# A vigência começa em 01/01/2019 conforme o plano DL-076 (HIPÓTESE, HI-83; a conferência
# da vigência está registrada em HI-90, item 1); o decreto é de 06/12/2018.

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

PALMAS_IBGE = "1721000"


def _semear_palmas(apps, schema_editor):
    RegraIssMunicipio = apps.get_model("fiscal", "RegraIssMunicipio")
    RegraIssMunicipio.objects.create(
        municipio_ibge=PALMAS_IBGE,
        nome="Palmas (TO)",
        dia_vencimento_proprio=10,
        dia_vencimento_retido=15,
        regra_dia_nao_util=(
            "Dia não útil: o vencimento passa para o primeiro dia útil seguinte "
            "(Decreto 1.667/2018, art. 86, § 3º)."
        ),
        fonte=(
            "Decreto 1.667/2018 (RCTM de Palmas), art. 86 § 3º e Anexo I — cópia íntegra em "
            "legisweb, consultada em 08/10/2026. Vigência desde 01/01/2019 (plano DL-076)."
        ),
        inicio_vigencia=datetime.date(2019, 1, 1),
        fim_vigencia=None,
    )


def _desfazer_palmas(apps, schema_editor):
    RegraIssMunicipio = apps.get_model("fiscal", "RegraIssMunicipio")
    RegraIssMunicipio.objects.filter(
        municipio_ibge=PALMAS_IBGE, inicio_vigencia=datetime.date(2019, 1, 1)
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        # 0007 e não a última de `empresas`, pela mesma razão das migrações 0003 e 0004: testes
        # que revertem `empresas` não podem desfazer esta migração sem reaplicá-la. Esta só
        # precisa de `empresas_empresa`, que existe desde 0001.
        ("empresas", "0007_bl54_cnpj_check_constraint_formato"),
        ("fiscal", "0005_dl075_situacao_iss_da_receita_informada"),
        ("tenancy", "0003_escritorio_endereco_no_timbre_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AliquotaIssMunicipal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "municipio_ibge",
                    models.CharField(max_length=7, verbose_name="código IBGE do município"),
                ),
                (
                    "subitem",
                    models.CharField(max_length=5, verbose_name="subitem da LC 116 (II.SS)"),
                ),
                (
                    "percentual",
                    models.DecimalField(
                        decimal_places=4, max_digits=5, verbose_name="alíquota (%)"
                    ),
                ),
                (
                    "fonte",
                    models.TextField(
                        verbose_name="fonte (dispositivo, documento e data de consulta)"
                    ),
                ),
                (
                    "inicio_vigencia",
                    models.DateField(verbose_name="início da vigência"),
                ),
                (
                    "fim_vigencia",
                    models.DateField(blank=True, null=True, verbose_name="fim da vigência"),
                ),
                (
                    "criada_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "alterada_em",
                    models.DateTimeField(auto_now=True, verbose_name="alterada em"),
                ),
                (
                    "alterada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="alterada por",
                    ),
                ),
                (
                    "criada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criada por",
                    ),
                ),
                (
                    "escritorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aliquotas_iss_municipal",
                        to="tenancy.escritorio",
                        verbose_name="escritório",
                    ),
                ),
            ],
            options={
                "verbose_name": "alíquota do ISS por município",
                "verbose_name_plural": "alíquotas do ISS por município",
                "ordering": [
                    "escritorio_id",
                    "municipio_ibge",
                    "subitem",
                    "inicio_vigencia",
                    "id",
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("municipio_ibge__regex", "^[0-9]{7}$")),
                        name="aliquota_iss_codigo_ibge",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "subitem__regex",
                                "^(0[1-9]|[12][0-9]|3[0-9]|40)\\.(0[1-9]|[1-9][0-9])$",
                            )
                        ),
                        name="aliquota_iss_subitem_valido",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("percentual__gt", 0), ("percentual__lte", 5)),
                        name="aliquota_iss_percentual_ate_5",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("fonte", ""), _negated=True),
                        name="aliquota_iss_fonte_preenchida",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("fim_vigencia__isnull", True),
                            ("fim_vigencia__gte", models.F("inicio_vigencia")),
                            _connector="OR",
                        ),
                        name="aliquota_iss_fim_depois_do_inicio",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegimeIssEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exercicio",
                    models.PositiveSmallIntegerField(verbose_name="exercício (ano-calendário)"),
                ),
                (
                    "regime",
                    models.CharField(
                        choices=[
                            ("aliquota", "Alíquota (apuração por nota)"),
                            ("fixo_autonomo", "Fixo de autônomo"),
                            (
                                "fixo_sociedade_profissionais",
                                "Fixo de sociedade de profissionais",
                            ),
                        ],
                        max_length=32,
                        verbose_name="regime do ISS",
                    ),
                ),
                (
                    "municipio_ibge",
                    models.CharField(
                        max_length=7,
                        verbose_name="código IBGE do município do estabelecimento",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "alterado_em",
                    models.DateTimeField(auto_now=True, verbose_name="alterado em"),
                ),
                (
                    "alterado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="alterado por",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regimes_iss",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "regime do ISS da empresa",
                "verbose_name_plural": "regimes do ISS das empresas",
                "ordering": ["empresa_id", "exercicio", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "exercicio"),
                        name="regime_iss_unico_por_empresa_exercicio",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("exercicio__gte", 2000), ("exercicio__lte", 2999)),
                        name="regime_iss_exercicio_valido",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "regime__in",
                                [
                                    "aliquota",
                                    "fixo_autonomo",
                                    "fixo_sociedade_profissionais",
                                ],
                            )
                        ),
                        name="regime_iss_regime_valido",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("municipio_ibge__regex", "^[0-9]{7}$")),
                        name="regime_iss_codigo_ibge",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegraIssMunicipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "municipio_ibge",
                    models.CharField(max_length=7, verbose_name="código IBGE do município"),
                ),
                ("nome", models.CharField(max_length=120, verbose_name="município")),
                (
                    "dia_vencimento_proprio",
                    models.PositiveSmallIntegerField(
                        verbose_name="dia do vencimento do ISS próprio (mês seguinte)"
                    ),
                ),
                (
                    "dia_vencimento_retido",
                    models.PositiveSmallIntegerField(
                        verbose_name="dia do vencimento do ISS retido (mês seguinte)"
                    ),
                ),
                (
                    "regra_dia_nao_util",
                    models.TextField(verbose_name="regra do dia não útil"),
                ),
                ("fonte", models.TextField(verbose_name="dispositivo e fonte")),
                (
                    "inicio_vigencia",
                    models.DateField(verbose_name="início da vigência"),
                ),
                (
                    "fim_vigencia",
                    models.DateField(blank=True, null=True, verbose_name="fim da vigência"),
                ),
                (
                    "criada_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "criada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "regra do ISS por município",
                "verbose_name_plural": "regras do ISS por município",
                "ordering": ["municipio_ibge", "inicio_vigencia", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("municipio_ibge__regex", "^[0-9]{7}$")),
                        name="regra_iss_codigo_ibge",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("dia_vencimento_proprio__gte", 1),
                            ("dia_vencimento_proprio__lte", 28),
                            ("dia_vencimento_retido__gte", 1),
                            ("dia_vencimento_retido__lte", 28),
                        ),
                        name="regra_iss_dias_entre_1_e_28",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("fim_vigencia__isnull", True),
                            ("fim_vigencia__gte", models.F("inicio_vigencia")),
                            _connector="OR",
                        ),
                        name="regra_iss_fim_depois_do_inicio",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("fonte", ""), _negated=True),
                        name="regra_iss_fonte_preenchida",
                    ),
                    models.UniqueConstraint(
                        fields=("municipio_ibge", "inicio_vigencia"),
                        name="regra_iss_unica_por_inicio",
                    ),
                ],
            },
        ),
        migrations.RunPython(_semear_palmas, _desfazer_palmas),
    ]
