# Generated by Django 6.1.2 on 2026-10-08 20:57

# DL-078 (frente A): escrituração das NFS-e TOMADAS (HI-93), em tabela PRÓPRIA. Aditiva:
# nenhuma tabela existente muda. Reverter é reverter esta migração e o merge.
#
# DEPENDÊNCIA: `fiscal 0007` e só `empresas 0007_bl54_cnpj_check_constraint_formato`. A
# escrituração precisa só da tabela `empresas_empresa` e da chave dela. Depender da última
# (0016) faz qualquer migração de teste que reverta `empresas` desfazer esta tabela, como a
# lição da DL-075 já registrou para a DL-072.
#
# Gatilhos de PostgreSQL, mesmo desenho da DL-072 (migração 0002): o Python recusa, e o banco
# recusa o que escapa do Python (`QuerySet.update()`, `bulk_create()`, SQL direto).
#
# 1. `escrituracao_tomada_vinculo_tomador_da_empresa`: a linha só aponta para um vínculo de
#    TOMADOR da MESMA empresa. Para a linha efetivada, `valor_servico`, `valor_liquido`,
#    `data_competencia` e `tp_ret_issqn` batem com o documento do vínculo (restrição
#    `escrituracao_tomada_efetivada_bate_com_o_documento`).
# 2. `escrituracao_tomada_imutavel_depois_de_efetivada`: transições rascunho→rascunho/efetivada;
#    efetivada→estornada, mudando SÓ as colunas do estorno; efetivada→efetivada, mudando SÓ as
#    colunas da data de pagamento (HI-96: a única alteração depois de efetivada); estornada não
#    muda mais; DELETE só de rascunho. A data de pagamento só pode mudar em nota efetivada.
#
# Só PostgreSQL: em SQLite vale a guarda do Python. Limite declarado: TRUNCATE não aciona
# gatilho de linha (mesmo limite da DL-052 e da DL-072).
#
# LIMITE DECLARADO (auditoria da DL-078, rodada 1, achado A9): o gatilho de INSERT de uma linha já
# efetivada confere o vínculo, `valor_servico`, `valor_liquido`, `data_competencia` e
# `tp_ret_issqn` contra o documento, mas NÃO confere `v_iss_qn`, `v_ret_cp`, `v_ret_irrf` nem
# `v_ret_csll` contra o XML guardado: o banco não lê o XML. Um INSERT direto com `v_iss_qn`
# forjado passa. Isso exige privilégio de ESCRITA no banco, que está fora do que a aplicação
# expõe; a integridade dos valores do XML depende desse privilégio, não do gatilho. Conferir
# contra o XML no gatilho exigiria copiar o XML para colunas, o que não se faz aqui.
#
# DATA DE PAGAMENTO LIMPA (HI-98, auditoria A1): limpar é um UPDATE que zera as colunas do grupo de
# pagamento (`data_pagamento`, `pagamento_informado_em`, `pagamento_informado_por_id`,
# `motivo_pagamento`). Passa pelo ramo efetivada→efetivada, que só aceita essas colunas; e a
# restrição `escrituracao_tomada_pagamento_com_informante` aceita data nula sem as demais. Por
# isso nenhuma regra nova foi preciso no banco. O motivo da limpeza fica na trilha da aplicação
# (`escrituracao_tomada.data_pagamento_limpa`), não em coluna.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

_SQL_FUNCAO_VINCULO = """
CREATE OR REPLACE FUNCTION fiscal_escrituracao_tomada_vinculo()
RETURNS trigger AS $$
DECLARE
    v_empresa_id fiscal_escrituracaotomada.empresa_id%TYPE;
    v_papel fiscal_vinculodocumentoempresa.papel%TYPE;
    v_serv fiscal_documentofiscal.v_serv%TYPE;
    v_liq fiscal_documentofiscal.v_liq%TYPE;
    v_competencia fiscal_documentofiscal.d_competencia%TYPE;
    v_tp_ret fiscal_documentofiscal.tp_ret_issqn%TYPE;
BEGIN
    SELECT v.empresa_id, v.papel, d.v_serv, d.v_liq, d.d_competencia, d.tp_ret_issqn
      INTO v_empresa_id, v_papel, v_serv, v_liq, v_competencia, v_tp_ret
      FROM fiscal_vinculodocumentoempresa AS v
      JOIN fiscal_documentofiscal AS d ON d.id = v.documento_id
     WHERE v.id = NEW.vinculo_id;
    IF NOT FOUND OR v_empresa_id <> NEW.empresa_id OR v_papel <> 'tomador' THEN
        RAISE EXCEPTION 'escrituração de tomada exige vínculo de tomador da mesma empresa'
            USING ERRCODE = '23514',
                  CONSTRAINT = 'escrituracao_tomada_vinculo_tomador_da_empresa';
    END IF;
    -- A linha efetivada carrega os valores do documento, e um INSERT que já nasce estornada
    -- também. O UPDATE de estorno e o de data de pagamento não mudam esses valores, então
    -- não são conferidos de novo (o documento pode ter mudado depois, e o estorno continua).
    IF (NEW.estado = 'efetivada' OR (TG_OP = 'INSERT' AND NEW.estado = 'estornada')) AND (
           (NEW.valor_servico IS NOT NULL AND NEW.valor_servico <> v_serv)
        OR (NEW.valor_liquido IS NOT NULL AND NEW.valor_liquido <> v_liq)
        OR (NEW.data_competencia IS NOT NULL AND NEW.data_competencia <> v_competencia)
        OR (NEW.tp_ret_issqn IS NOT NULL AND NEW.tp_ret_issqn <> v_tp_ret)
    ) THEN
        RAISE EXCEPTION 'escrituração de tomada precisa ter os valores do documento de origem'
            USING ERRCODE = '23514',
                  CONSTRAINT = 'escrituracao_tomada_efetivada_bate_com_o_documento';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

_SQL_GATILHO_VINCULO = """
CREATE TRIGGER trg_escrituracao_tomada_vinculo
BEFORE INSERT OR UPDATE ON fiscal_escrituracaotomada
FOR EACH ROW EXECUTE FUNCTION fiscal_escrituracao_tomada_vinculo();
"""

_SQL_FUNCAO_IMUTAVEL = """
CREATE OR REPLACE FUNCTION fiscal_escrituracao_tomada_imutavel()
RETURNS trigger AS $$
DECLARE
    colunas_do_estorno text[] := ARRAY[
        'estado', 'estornada_em', 'estornada_por_id', 'motivo_estorno'
    ];
    colunas_do_pagamento text[] := ARRAY[
        'data_pagamento', 'pagamento_informado_em', 'pagamento_informado_por_id',
        'motivo_pagamento'
    ];
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.estado <> 'rascunho' THEN
            RAISE EXCEPTION 'escrituração de tomada efetivada ou estornada não pode ser excluída'
                USING ERRCODE = '23514',
                      CONSTRAINT = 'escrituracao_tomada_imutavel_depois_de_efetivada';
        END IF;
        RETURN OLD;
    END IF;

    IF OLD.estado = 'rascunho' AND NEW.estado IN ('rascunho', 'efetivada') THEN
        -- A data de pagamento é de nota efetivada: no rascunho ela não pode mudar.
        IF NEW.data_pagamento IS DISTINCT FROM OLD.data_pagamento AND NEW.estado <> 'efetivada' THEN
            RAISE EXCEPTION 'data de pagamento só pode ser informada em nota efetivada'
                USING ERRCODE = '23514',
                      CONSTRAINT = 'escrituracao_tomada_imutavel_depois_de_efetivada';
        END IF;
        RETURN NEW;
    END IF;

    IF OLD.estado = 'efetivada' AND NEW.estado = 'estornada' THEN
        IF (to_jsonb(NEW) - colunas_do_estorno)
           IS DISTINCT FROM (to_jsonb(OLD) - colunas_do_estorno) THEN
            RAISE EXCEPTION
                'escrituração de tomada efetivada só pode ser estornada; os dados do ato não mudam'
                USING ERRCODE = '23514',
                      CONSTRAINT = 'escrituracao_tomada_imutavel_depois_de_efetivada';
        END IF;
        RETURN NEW;
    END IF;

    IF OLD.estado = 'efetivada' AND NEW.estado = 'efetivada' THEN
        -- Só a data de pagamento (e as colunas que a acompanham) pode mudar. Qualquer outra
        -- coluna continua imutável: a correção é o estorno com motivo.
        IF (to_jsonb(NEW) - colunas_do_pagamento)
           IS DISTINCT FROM (to_jsonb(OLD) - colunas_do_pagamento) THEN
            RAISE EXCEPTION
                'escrituração de tomada efetivada só aceita a data de pagamento; estorne o resto'
                USING ERRCODE = '23514',
                      CONSTRAINT = 'escrituracao_tomada_imutavel_depois_de_efetivada';
        END IF;
        RETURN NEW;
    END IF;

    RAISE EXCEPTION
        'transição de estado da escrituração de tomada não permitida: % -> %',
        OLD.estado, NEW.estado
        USING ERRCODE = '23514',
              CONSTRAINT = 'escrituracao_tomada_imutavel_depois_de_efetivada';
END;
$$ LANGUAGE plpgsql;
"""

_SQL_GATILHO_IMUTAVEL = """
CREATE TRIGGER trg_escrituracao_tomada_imutavel
BEFORE UPDATE OR DELETE ON fiscal_escrituracaotomada
FOR EACH ROW EXECUTE FUNCTION fiscal_escrituracao_tomada_imutavel();
"""

_SQL_DESFAZER = """
DROP TRIGGER IF EXISTS trg_escrituracao_tomada_imutavel ON fiscal_escrituracaotomada;
DROP TRIGGER IF EXISTS trg_escrituracao_tomada_vinculo ON fiscal_escrituracaotomada;
DROP FUNCTION IF EXISTS fiscal_escrituracao_tomada_imutavel();
DROP FUNCTION IF EXISTS fiscal_escrituracao_tomada_vinculo();
"""


def _criar_gatilhos(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for sql in (
        _SQL_FUNCAO_VINCULO,
        _SQL_GATILHO_VINCULO,
        _SQL_FUNCAO_IMUTAVEL,
        _SQL_GATILHO_IMUTAVEL,
    ):
        schema_editor.execute(sql, params=None)


def _desfazer_gatilhos(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(_SQL_DESFAZER, params=None)


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0007_bl54_cnpj_check_constraint_formato"),
        ("fiscal", "0007_dl076_piso_aliquota_iss"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EscrituracaoTomada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "natureza",
                    models.CharField(
                        choices=[
                            (
                                "tomado_iss_retido_pelo_cliente",
                                "Tomado — ISS retido pelo cliente tomador (T1)",
                            ),
                            (
                                "tomado_sem_retencao",
                                "Tomado — ISS do prestador, sem retenção (T2)",
                            ),
                            (
                                "tomado_prestador_outro_municipio",
                                "Tomado — prestador de outro município (T3)",
                            ),
                            ("tomado_de_mei", "Tomado de MEI (T5)"),
                            (
                                "tomado_de_simples",
                                "Tomado de ME/EPP do Simples Nacional (T6)",
                            ),
                            ("tomado_de_pessoa_fisica", "Tomado de pessoa física (T7)"),
                        ],
                        max_length=40,
                        verbose_name="natureza da operação",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("efetivada", "Efetivada"),
                            ("estornada", "Estornada"),
                        ],
                        default="rascunho",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                (
                    "data_emissao",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="data de emissão (dia do dhEmi)",
                    ),
                ),
                (
                    "data_competencia",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="data de competência (dCompet)",
                    ),
                ),
                (
                    "prestador_tipo_documento",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="tipo de documento do prestador",
                    ),
                ),
                (
                    "tp_emit",
                    models.CharField(
                        blank=True,
                        max_length=1,
                        null=True,
                        verbose_name="emitente da DPS (tpEmit)",
                    ),
                ),
                (
                    "tp_ret_issqn",
                    models.CharField(
                        blank=True,
                        max_length=1,
                        null=True,
                        verbose_name="tipo de retenção do ISSQN (tpRetISSQN)",
                    ),
                ),
                (
                    "c_loc_incid",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        verbose_name="município de incidência (cLocIncid)",
                    ),
                ),
                (
                    "op_simp_nac",
                    models.CharField(
                        blank=True,
                        max_length=1,
                        null=True,
                        verbose_name="situação no Simples Nacional (opSimpNac)",
                    ),
                ),
                (
                    "reg_ap_trib_sn",
                    models.CharField(
                        blank=True,
                        max_length=1,
                        null=True,
                        verbose_name="regime de apuração no Simples (regApTribSN)",
                    ),
                ),
                (
                    "valor_servico",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=17,
                        null=True,
                        verbose_name="valor do serviço (vServ)",
                    ),
                ),
                (
                    "valor_liquido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=17,
                        null=True,
                        verbose_name="valor líquido (vLiq)",
                    ),
                ),
                (
                    "v_desc_incond",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=17,
                        null=True,
                        verbose_name="desconto incondicionado (vDescIncond)",
                    ),
                ),
                (
                    "v_desc_cond",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=17,
                        null=True,
                        verbose_name="desconto condicionado (vDescCond)",
                    ),
                ),
                (
                    "v_iss_qn",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=17,
                        null=True,
                        verbose_name="ISSQN destacado (vISSQN)",
                    ),
                ),
                (
                    "v_ret_cp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=17,
                        null=True,
                        verbose_name="contribuição previdenciária retida (vRetCP)",
                    ),
                ),
                (
                    "v_ret_irrf",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=17,
                        null=True,
                        verbose_name="IRRF retido (vRetIRRF)",
                    ),
                ),
                (
                    "v_ret_csll",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=17,
                        null=True,
                        verbose_name="CSLL retida, com PIS e COFINS somados (vRetCSLL)",
                    ),
                ),
                (
                    "tp_ret_pis_cofins",
                    models.CharField(
                        blank=True,
                        max_length=1,
                        null=True,
                        verbose_name="tipo de retenção do PIS/COFINS (tpRetPisCofins)",
                    ),
                ),
                (
                    "v_pis",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=17,
                        null=True,
                        verbose_name="PIS, débito próprio do prestador (vPis)",
                    ),
                ),
                (
                    "v_cofins",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=17,
                        null=True,
                        verbose_name="COFINS, débito próprio do prestador (vCofins)",
                    ),
                ),
                (
                    "efetivada_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="efetivada em"),
                ),
                (
                    "estornada_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="estornada em"),
                ),
                (
                    "motivo_estorno",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="motivo do estorno",
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="data de pagamento informada",
                    ),
                ),
                (
                    "pagamento_informado_em",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="data de pagamento informada em",
                    ),
                ),
                (
                    "motivo_pagamento",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="motivo da data de pagamento",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criada por",
                    ),
                ),
                (
                    "efetivada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="efetivada por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escrituracoes_tomadas",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "estornada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="estornada por",
                    ),
                ),
                (
                    "pagamento_informado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="pagamento informado por",
                    ),
                ),
                (
                    "vinculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escrituracoes_tomadas",
                        to="fiscal.vinculodocumentoempresa",
                        verbose_name="vínculo documento-empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "escrituração de nota tomada",
                "verbose_name_plural": "escriturações de notas tomadas",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("estado__in", ["rascunho", "efetivada"])),
                        fields=("vinculo",),
                        name="escrituracao_tomada_ativa_unica_por_vinculo",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("estado__in", ["rascunho", "efetivada", "estornada"])),
                        name="escrituracao_tomada_estado_valido",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("efetivada_em__isnull", True),
                                ("efetivada_por__isnull", True),
                                ("estado", "rascunho"),
                                ("estornada_em__isnull", True),
                                ("estornada_por__isnull", True),
                                ("motivo_estorno", ""),
                            ),
                            models.Q(
                                ("data_competencia__isnull", False),
                                ("data_emissao__isnull", False),
                                ("efetivada_em__isnull", False),
                                ("efetivada_por__isnull", False),
                                ("estado", "efetivada"),
                                ("estornada_em__isnull", True),
                                ("estornada_por__isnull", True),
                                ("motivo_estorno", ""),
                                ("tp_emit__isnull", False),
                                ("tp_ret_issqn__isnull", False),
                                ("valor_liquido__isnull", False),
                                ("valor_servico__isnull", False),
                            ),
                            models.Q(
                                models.Q(("motivo_estorno", ""), _negated=True),
                                ("data_competencia__isnull", False),
                                ("data_emissao__isnull", False),
                                ("efetivada_em__isnull", False),
                                ("efetivada_por__isnull", False),
                                ("estado", "estornada"),
                                ("estornada_em__isnull", False),
                                ("estornada_por__isnull", False),
                                ("tp_emit__isnull", False),
                                ("tp_ret_issqn__isnull", False),
                                ("valor_liquido__isnull", False),
                                ("valor_servico__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="escrituracao_tomada_campos_coerentes_com_o_estado",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("data_pagamento__isnull", True),
                            models.Q(
                                ("data_pagamento__isnull", False),
                                ("pagamento_informado_em__isnull", False),
                                ("pagamento_informado_por__isnull", False),
                                models.Q(("motivo_pagamento", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="escrituracao_tomada_pagamento_com_informante",
                    ),
                ],
            },
        ),
        migrations.RunPython(_criar_gatilhos, _desfazer_gatilhos),
    ]
