# Generated by Django 6.1.2 on 2026-10-08

# DL-079 (frente A): Lucro Presumido, IRPJ e CSLL trimestrais com o acréscimo da LC 224. Aditiva:
# só cria tabelas novas; nenhuma existente muda. Reverter é reverter esta migração e o merge.
#
# DEPENDÊNCIA: `fiscal 0008` e só `empresas 0007_bl54_cnpj_check_constraint_formato`. As tabelas
# novas precisam só de `empresas_empresa` e da chave dela (mesma lição da DL-078: depender da
# última `empresas` faz reverter `empresas` desfazer esta tabela).
#
# Gatilhos de PostgreSQL, no mesmo desenho da DL-072 (0002) e da DL-078 (0008): o Python recusa, e
# o banco recusa o que escapa do Python (`QuerySet.update()`, `bulk_create()`, SQL direto).
#   1. `presumido_receita_guarda`: a receita só nasce ativa, com atividade da MESMA empresa (quando
#      houver); depois, só o estorno (ativa→estornada, mudando as colunas do estorno); não se apaga.
#   2. `presumido_declaracao_guarda`: a declaração de integrais é um fato gravado; não muda nem
#      se apaga.
#   3. `presumido_confirmacao_guarda`: nasce ativa, só para escrituração EFETIVADA; depois só vai de
#      ativa a substituída; não se apaga.
#   4. `presumido_medida_guarda`: a medida não muda, exceto a revogação (ativa→inativa, com motivo).
#
# Só PostgreSQL: em SQLite vale a guarda do Python. Limite declarado: TRUNCATE não aciona gatilho de
# linha (mesmo limite da DL-052, DL-072 e DL-078). Quem tem privilégio de dono da tabela fica
# fora do
# que o banco impede sozinho.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

_SQL_FUNCAO_RECEITA = """
CREATE OR REPLACE FUNCTION fiscal_presumido_receita_guarda()
RETURNS trigger AS $$
DECLARE
    v_empresa_da_atividade fiscal_atividadepresuncaoempresa.empresa_id%TYPE;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'receita trimestral do presumido não pode ser excluída; estorne com motivo'
            USING ERRCODE = '23514', CONSTRAINT = 'presumido_receita_imutavel';
    END IF;
    IF TG_OP = 'INSERT' THEN
        IF NEW.atividade_id IS NOT NULL THEN
            SELECT a.empresa_id INTO v_empresa_da_atividade
              FROM fiscal_atividadepresuncaoempresa AS a WHERE a.id = NEW.atividade_id;
            IF v_empresa_da_atividade IS DISTINCT FROM NEW.empresa_id THEN
                RAISE EXCEPTION 'atividade de presunção de outra empresa'
                    USING ERRCODE = '23514', CONSTRAINT = 'presumido_receita_atividade_da_empresa';
            END IF;
        END IF;
        IF NEW.estado <> 'ativa' THEN
            RAISE EXCEPTION 'receita trimestral do presumido nasce ativa'
                USING ERRCODE = '23514', CONSTRAINT = 'presumido_receita_imutavel';
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.estado = 'ativa' AND NEW.estado = 'estornada' THEN
        IF (to_jsonb(NEW) - ARRAY['estado', 'motivo_estorno', 'estornada_em', 'estornada_por_id'])
           IS DISTINCT FROM
           (to_jsonb(OLD) - ARRAY['estado', 'motivo_estorno', 'estornada_em', 'estornada_por_id'])
           THEN
            RAISE EXCEPTION 'receita do presumido só aceita o estorno; os dados do ato não mudam'
                USING ERRCODE = '23514', CONSTRAINT = 'presumido_receita_imutavel';
        END IF;
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'receita trimestral do presumido só pode ser estornada'
        USING ERRCODE = '23514', CONSTRAINT = 'presumido_receita_imutavel';
END;
$$ LANGUAGE plpgsql;
"""

_SQL_GATILHO_RECEITA = """
CREATE TRIGGER trg_presumido_receita_guarda
BEFORE INSERT OR UPDATE OR DELETE ON fiscal_receitatrimestralpresumido
FOR EACH ROW EXECUTE FUNCTION fiscal_presumido_receita_guarda();
"""

_SQL_FUNCAO_DECLARACAO = """
CREATE OR REPLACE FUNCTION fiscal_presumido_declaracao_guarda()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'declaração de receitas integrais é um fato gravado; não muda nem se apaga'
        USING ERRCODE = '23514', CONSTRAINT = 'presumido_declaracao_imutavel';
END;
$$ LANGUAGE plpgsql;
"""

_SQL_GATILHO_DECLARACAO = """
CREATE TRIGGER trg_presumido_declaracao_guarda
BEFORE UPDATE OR DELETE ON fiscal_declaracaoreceitasintegrais
FOR EACH ROW EXECUTE FUNCTION fiscal_presumido_declaracao_guarda();
"""

_SQL_FUNCAO_CONFIRMACAO = """
CREATE OR REPLACE FUNCTION fiscal_presumido_confirmacao_guarda()
RETURNS trigger AS $$
DECLARE
    v_estado_escrituracao fiscal_escrituracaofiscal.estado%TYPE;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'confirmação de retenção não pode ser excluída; confirme de novo'
            USING ERRCODE = '23514', CONSTRAINT = 'presumido_confirmacao_imutavel';
    END IF;
    IF TG_OP = 'INSERT' THEN
        SELECT e.estado INTO v_estado_escrituracao
          FROM fiscal_escrituracaofiscal AS e WHERE e.id = NEW.escrituracao_id;
        IF v_estado_escrituracao IS DISTINCT FROM 'efetivada' OR NEW.estado <> 'ativa' THEN
            RAISE EXCEPTION 'confirmação de retenção exige escrituração efetivada'
                USING ERRCODE = '23514', CONSTRAINT = 'presumido_confirmacao_imutavel';
        END IF;
        RETURN NEW;
    END IF;
    IF OLD.estado = 'ativa' AND NEW.estado = 'substituida'
       AND (to_jsonb(NEW) - 'estado') IS NOT DISTINCT FROM (to_jsonb(OLD) - 'estado') THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'confirmação de retenção só pode ser substituída'
        USING ERRCODE = '23514', CONSTRAINT = 'presumido_confirmacao_imutavel';
END;
$$ LANGUAGE plpgsql;
"""

_SQL_GATILHO_CONFIRMACAO = """
CREATE TRIGGER trg_presumido_confirmacao_guarda
BEFORE INSERT OR UPDATE OR DELETE ON fiscal_confirmacaoretencaopresumido
FOR EACH ROW EXECUTE FUNCTION fiscal_presumido_confirmacao_guarda();
"""

_SQL_FUNCAO_MEDIDA = """
CREATE OR REPLACE FUNCTION fiscal_presumido_medida_guarda()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'medida judicial não pode ser excluída; revogue com motivo'
            USING ERRCODE = '23514', CONSTRAINT = 'presumido_medida_imutavel';
    END IF;
    IF OLD.ativa AND NOT NEW.ativa
       AND (to_jsonb(NEW) - ARRAY['ativa', 'revogada_em', 'motivo_revogacao'])
           IS NOT DISTINCT FROM
           (to_jsonb(OLD) - ARRAY['ativa', 'revogada_em', 'motivo_revogacao']) THEN
        RETURN NEW;
    END IF;
    RAISE EXCEPTION 'medida judicial só pode ser revogada; os dados não mudam'
        USING ERRCODE = '23514', CONSTRAINT = 'presumido_medida_imutavel';
END;
$$ LANGUAGE plpgsql;
"""

_SQL_GATILHO_MEDIDA = """
CREATE TRIGGER trg_presumido_medida_guarda
BEFORE UPDATE OR DELETE ON fiscal_medidajudiciallc224
FOR EACH ROW EXECUTE FUNCTION fiscal_presumido_medida_guarda();
"""

_SQL_DESFAZER = """
DROP TRIGGER IF EXISTS trg_presumido_medida_guarda ON fiscal_medidajudiciallc224;
DROP TRIGGER IF EXISTS trg_presumido_confirmacao_guarda ON fiscal_confirmacaoretencaopresumido;
DROP TRIGGER IF EXISTS trg_presumido_declaracao_guarda ON fiscal_declaracaoreceitasintegrais;
DROP TRIGGER IF EXISTS trg_presumido_receita_guarda ON fiscal_receitatrimestralpresumido;
DROP FUNCTION IF EXISTS fiscal_presumido_medida_guarda();
DROP FUNCTION IF EXISTS fiscal_presumido_confirmacao_guarda();
DROP FUNCTION IF EXISTS fiscal_presumido_declaracao_guarda();
DROP FUNCTION IF EXISTS fiscal_presumido_receita_guarda();
"""


def _criar_gatilhos(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for sql in (
        _SQL_FUNCAO_RECEITA,
        _SQL_GATILHO_RECEITA,
        _SQL_FUNCAO_DECLARACAO,
        _SQL_GATILHO_DECLARACAO,
        _SQL_FUNCAO_CONFIRMACAO,
        _SQL_GATILHO_CONFIRMACAO,
        _SQL_FUNCAO_MEDIDA,
        _SQL_GATILHO_MEDIDA,
    ):
        schema_editor.execute(sql, params=None)


def _desfazer_gatilhos(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(_SQL_DESFAZER, params=None)


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0007_bl54_cnpj_check_constraint_formato"),
        ("fiscal", "0008_dl078_escrituracao_tomada"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AtividadePresuncaoEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atividade",
                    models.CharField(
                        choices=[
                            (
                                "comercio_industria_transporte_carga",
                                "Comércio, indústria e transporte de cargas",
                            ),
                            ("revenda_combustiveis", "Revenda de combustíveis"),
                            ("transporte_passageiros", "Transporte de passageiros"),
                            ("servicos_gerais", "Serviços em geral"),
                            ("intermediacao_negocios", "Intermediação de negócios"),
                            (
                                "administracao_locacao_cessao_bens",
                                "Administração, locação e cessão de bens",
                            ),
                            ("servicos_hospitalares", "Serviços hospitalares"),
                        ],
                        max_length=40,
                        verbose_name="atividade de presunção",
                    ),
                ),
                ("inicio", models.DateField(verbose_name="início da vigência")),
                (
                    "fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="fim da vigência"
                    ),
                ),
                (
                    "padrao",
                    models.BooleanField(
                        default=False, verbose_name="atividade padrão das NFS-e"
                    ),
                ),
                (
                    "requisitos_hospitalares_confirmados",
                    models.BooleanField(
                        default=False,
                        verbose_name="requisitos do serviço hospitalar confirmados pelo contador",
                    ),
                ),
                (
                    "criada_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "criada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criada por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atividades_presuncao",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "atividade de presunção da empresa",
                "verbose_name_plural": "atividades de presunção da empresa",
                "ordering": ["empresa_id", "inicio", "id"],
            },
        ),
        migrations.CreateModel(
            name="ConfirmacaoRetencaoPresumido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "irrf_confirmado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="IRRF confirmado",
                    ),
                ),
                (
                    "csll_confirmada",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="CSLL confirmada",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="motivo (obrigatório quando o valor difere do proposto)",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ativa", "Ativa"), ("substituida", "Substituída")],
                        default="ativa",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                (
                    "confirmada_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="confirmada em"
                    ),
                ),
                (
                    "confirmada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="confirmada por",
                    ),
                ),
                (
                    "escrituracao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmacoes_retencao_presumido",
                        to="fiscal.escrituracaofiscal",
                        verbose_name="escrituração prestada",
                    ),
                ),
            ],
            options={
                "verbose_name": "confirmação de retenção do presumido",
                "verbose_name_plural": "confirmações de retenção do presumido",
                "ordering": ["escrituracao_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="CriterioReceitaPresumido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ano",
                    models.PositiveSmallIntegerField(verbose_name="ano-calendário"),
                ),
                (
                    "criterio",
                    models.CharField(
                        choices=[("competencia", "Competência"), ("caixa", "Caixa")],
                        max_length=12,
                        verbose_name="critério",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="criterios_receita_presumido",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "critério de receita do presumido",
                "verbose_name_plural": "critérios de receita do presumido",
            },
        ),
        migrations.CreateModel(
            name="DeclaracaoReceitasIntegrais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ano",
                    models.PositiveSmallIntegerField(verbose_name="ano-calendário"),
                ),
                (
                    "trimestre",
                    models.PositiveSmallIntegerField(verbose_name="trimestre (1 a 4)"),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="total das integrais declaradas",
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="observação",
                    ),
                ),
                (
                    "declarada_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="declarada em"
                    ),
                ),
                (
                    "declarada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="declarada por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="declaracoes_integrais_presumido",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "declaração de receitas integrais",
                "verbose_name_plural": "declarações de receitas integrais",
                "ordering": ["empresa_id", "ano", "trimestre", "id"],
            },
        ),
        migrations.CreateModel(
            name="MedidaJudicialLC224",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tributo",
                    models.CharField(
                        choices=[
                            ("irpj", "IRPJ"),
                            ("csll", "CSLL"),
                            ("ambos", "IRPJ e CSLL"),
                        ],
                        max_length=10,
                        verbose_name="tributo",
                    ),
                ),
                (
                    "ano_inicial",
                    models.PositiveSmallIntegerField(verbose_name="ano inicial"),
                ),
                (
                    "trimestre_inicial",
                    models.PositiveSmallIntegerField(
                        verbose_name="trimestre inicial (1 a 4)"
                    ),
                ),
                (
                    "ano_final",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="ano final"
                    ),
                ),
                (
                    "trimestre_final",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="trimestre final (1 a 4)"
                    ),
                ),
                (
                    "numero_processo",
                    models.CharField(max_length=60, verbose_name="número do processo"),
                ),
                (
                    "orgao",
                    models.CharField(max_length=200, verbose_name="órgão judicial"),
                ),
                ("data_decisao", models.DateField(verbose_name="data da decisão")),
                (
                    "deposito_judicial",
                    models.BooleanField(
                        default=False, verbose_name="depósito judicial"
                    ),
                ),
                (
                    "suporte",
                    models.CharField(
                        max_length=300, verbose_name="documento de suporte"
                    ),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "revogada_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="revogada em"
                    ),
                ),
                (
                    "motivo_revogacao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="motivo da revogação",
                    ),
                ),
                (
                    "criada_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "criada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criada por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medidas_judiciais_lc224",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "medida judicial contra a LC 224",
                "verbose_name_plural": "medidas judiciais contra a LC 224",
                "ordering": ["empresa_id", "ano_inicial", "trimestre_inicial", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReceitaTrimestralPresumido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ano",
                    models.PositiveSmallIntegerField(verbose_name="ano-calendário"),
                ),
                (
                    "trimestre",
                    models.PositiveSmallIntegerField(verbose_name="trimestre (1 a 4)"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("presuncao", "Sujeita à presunção"),
                            ("integral", "Integral (art. 25, II da Lei 9.430/1996)"),
                        ],
                        max_length=10,
                        verbose_name="tipo da receita",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=300, verbose_name="descrição"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="valor"
                    ),
                ),
                (
                    "suporte",
                    models.CharField(
                        max_length=300, verbose_name="documento de suporte"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ativa", "Ativa"), ("estornada", "Estornada")],
                        default="ativa",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "motivo_estorno",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="motivo do estorno",
                    ),
                ),
                (
                    "estornada_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="estornada em"
                    ),
                ),
                (
                    "criada_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criada em"),
                ),
                (
                    "atividade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receitas_trimestrais",
                        to="fiscal.atividadepresuncaoempresa",
                        verbose_name="atividade de presunção",
                    ),
                ),
                (
                    "criada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="criada por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receitas_trimestrais_presumido",
                        to="empresas.empresa",
                        verbose_name="empresa",
                    ),
                ),
                (
                    "estornada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="estornada por",
                    ),
                ),
            ],
            options={
                "verbose_name": "receita trimestral do presumido",
                "verbose_name_plural": "receitas trimestrais do presumido",
                "ordering": ["empresa_id", "ano", "trimestre", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="atividadepresuncaoempresa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fim__isnull", True),
                    ("fim__gte", models.F("inicio")),
                    _connector="OR",
                ),
                name="presumido_atividade_fim_depois_do_inicio",
            ),
        ),
        migrations.AddConstraint(
            model_name="atividadepresuncaoempresa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "atividade__in",
                        [
                            "comercio_industria_transporte_carga",
                            "revenda_combustiveis",
                            "transporte_passageiros",
                            "servicos_gerais",
                            "intermediacao_negocios",
                            "administracao_locacao_cessao_bens",
                            "servicos_hospitalares",
                        ],
                    )
                ),
                name="presumido_atividade_valida",
            ),
        ),
        migrations.AddConstraint(
            model_name="atividadepresuncaoempresa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("atividade", "servicos_hospitalares"), _negated=True),
                    ("requisitos_hospitalares_confirmados", True),
                    _connector="OR",
                ),
                name="presumido_hospitalar_exige_requisitos",
            ),
        ),
        migrations.AddConstraint(
            model_name="atividadepresuncaoempresa",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fim__isnull", True), ("padrao", True)),
                fields=("empresa",),
                name="presumido_padrao_unica_em_aberto",
            ),
        ),
        migrations.AddConstraint(
            model_name="confirmacaoretencaopresumido",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "ativa")),
                fields=("escrituracao",),
                name="presumido_confirmacao_ativa_unica_por_escrituracao",
            ),
        ),
        migrations.AddConstraint(
            model_name="confirmacaoretencaopresumido",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("irrf_confirmado__isnull", True),
                    ("irrf_confirmado__gte", 0),
                    _connector="OR",
                ),
                name="presumido_confirmacao_irrf_nao_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="confirmacaoretencaopresumido",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("csll_confirmada__isnull", True),
                    ("csll_confirmada__gte", 0),
                    _connector="OR",
                ),
                name="presumido_confirmacao_csll_nao_negativa",
            ),
        ),
        migrations.AddConstraint(
            model_name="confirmacaoretencaopresumido",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("irrf_confirmado__isnull", False),
                    ("csll_confirmada__isnull", False),
                    _connector="OR",
                ),
                name="presumido_confirmacao_ao_menos_um_valor",
            ),
        ),
        migrations.AddConstraint(
            model_name="confirmacaoretencaopresumido",
            constraint=models.CheckConstraint(
                condition=models.Q(("estado__in", ["ativa", "substituida"])),
                name="presumido_confirmacao_estado_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="criterioreceitapresumido",
            constraint=models.UniqueConstraint(
                fields=("empresa", "ano"), name="presumido_criterio_unico_por_ano"
            ),
        ),
        migrations.AddConstraint(
            model_name="criterioreceitapresumido",
            constraint=models.CheckConstraint(
                condition=models.Q(("criterio__in", ["competencia", "caixa"])),
                name="presumido_criterio_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="criterioreceitapresumido",
            constraint=models.CheckConstraint(
                condition=models.Q(("ano__gte", 1970), ("ano__lte", 2999)),
                name="presumido_criterio_ano_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="declaracaoreceitasintegrais",
            constraint=models.CheckConstraint(
                condition=models.Q(("trimestre__gte", 1), ("trimestre__lte", 4)),
                name="presumido_declaracao_trimestre_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="declaracaoreceitasintegrais",
            constraint=models.CheckConstraint(
                condition=models.Q(("total__gte", 0)),
                name="presumido_declaracao_total_nao_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="medidajudiciallc224",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("trimestre_inicial__gte", 1), ("trimestre_inicial__lte", 4)
                ),
                name="presumido_medida_trimestre_inicial_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="medidajudiciallc224",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("trimestre_final__isnull", True),
                    models.Q(("trimestre_final__gte", 1), ("trimestre_final__lte", 4)),
                    _connector="OR",
                ),
                name="presumido_medida_trimestre_final_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="medidajudiciallc224",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("ano_final__isnull", True), ("trimestre_final__isnull", True)
                    ),
                    models.Q(
                        ("ano_final__isnull", False), ("trimestre_final__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="presumido_medida_fim_completo_ou_indeterminado",
            ),
        ),
        migrations.AddConstraint(
            model_name="medidajudiciallc224",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ano_final__isnull", True),
                    ("ano_final__gt", models.F("ano_inicial")),
                    models.Q(
                        ("ano_final", models.F("ano_inicial")),
                        ("trimestre_final__gte", models.F("trimestre_inicial")),
                    ),
                    _connector="OR",
                ),
                name="presumido_medida_fim_depois_do_inicio",
            ),
        ),
        migrations.AddConstraint(
            model_name="medidajudiciallc224",
            constraint=models.CheckConstraint(
                condition=models.Q(("tributo__in", ["irpj", "csll", "ambos"])),
                name="presumido_medida_tributo_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="medidajudiciallc224",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("ativa", True),
                        ("motivo_revogacao", ""),
                        ("revogada_em__isnull", True),
                    ),
                    models.Q(
                        models.Q(("motivo_revogacao", ""), _negated=True),
                        ("ativa", False),
                        ("revogada_em__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="presumido_medida_ativa_coerente",
            ),
        ),
        migrations.AddConstraint(
            model_name="receitatrimestralpresumido",
            constraint=models.CheckConstraint(
                condition=models.Q(("trimestre__gte", 1), ("trimestre__lte", 4)),
                name="presumido_receita_trimestre_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="receitatrimestralpresumido",
            constraint=models.CheckConstraint(
                condition=models.Q(("ano__gte", 1970), ("ano__lte", 2999)),
                name="presumido_receita_ano_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="receitatrimestralpresumido",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("atividade__isnull", False), ("tipo", "presuncao")),
                    models.Q(("atividade__isnull", True), ("tipo", "integral")),
                    _connector="OR",
                ),
                name="presumido_receita_atividade_conforme_tipo",
            ),
        ),
        migrations.AddConstraint(
            model_name="receitatrimestralpresumido",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor__gt", 0)),
                name="presumido_receita_valor_positivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="receitatrimestralpresumido",
            constraint=models.CheckConstraint(
                condition=models.Q(("suporte", ""), _negated=True),
                name="presumido_receita_suporte_obrigatorio",
            ),
        ),
        migrations.AddConstraint(
            model_name="receitatrimestralpresumido",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("estado", "ativa"),
                        ("estornada_em__isnull", True),
                        ("estornada_por__isnull", True),
                        ("motivo_estorno", ""),
                    ),
                    models.Q(
                        models.Q(("motivo_estorno", ""), _negated=True),
                        ("estado", "estornada"),
                        ("estornada_em__isnull", False),
                        ("estornada_por__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="presumido_receita_estado_coerente",
            ),
        ),
        migrations.RunPython(_criar_gatilhos, _desfazer_gatilhos),
    ]
