# DL-085 (frente A), migração ADITIVA: o lote de escrituração de NF-e em volume (RC-173).
#
# Cria duas tabelas novas e nenhuma alteração em tabela existente:
#
# 1. `LoteEscrituracaoNFe`: um lote por empresa e mês, com a assinatura da prévia confirmada, as
#    escolhas de natureza por grupo, quem confirmou e o estado (em andamento ou concluído). Um lote
#    em andamento por empresa e mês, no máximo (restrição parcial no banco).
# 2. `LoteEscrituracaoNFeNota`: as notas do conjunto confirmado, com as naturezas fixadas na
#    confirmação e o estado de cada uma (pendente, efetivada, já efetivada ou falhou).
#
# Reversão: `migrate fiscal 0012` remove as duas tabelas. Isso apaga o REGISTRO dos lotes (quais
# notas o contador confirmou em bloco) e nada mais: as escriturações efetivadas por lote continuam
# válidas, porque são as mesmas da escrituração individual (DL-081), e a trilha de auditoria
# (`RegistroAuditoria`) fica intacta. Reaplicar a migração recria tabelas vazias.
#
# A migração foi gerada pelo Django e não tem SQL manual.
# Generated by Django 6.1.2 on 2026-10-09 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0016_dl074_data_abertura_cnpj"),
        ("fiscal", "0012_dl083_combustivel_revenda"),
        ("tenancy", "0003_escritorio_endereco_no_timbre_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoteEscrituracaoNFe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competencia",
                    models.DateField(verbose_name="competência (primeiro dia do mês)"),
                ),
                (
                    "assinatura",
                    models.CharField(
                        max_length=64, verbose_name="assinatura da prévia"
                    ),
                ),
                (
                    "escolhas",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="escolhas de natureza por grupo",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("em_andamento", "Em andamento"),
                            ("concluido", "Concluído"),
                        ],
                        default="em_andamento",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                (
                    "quantidade_notas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="notas confirmadas"
                    ),
                ),
                (
                    "quantidade_itens",
                    models.PositiveIntegerField(
                        default=0, verbose_name="itens confirmados"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "concluido_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="concluído em"
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="confirmado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes_escrituracao_nfe",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "escritorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes_escrituracao_nfe",
                        to="tenancy.escritorio",
                    ),
                ),
            ],
            options={
                "verbose_name": "lote de escrituração de NF-e",
                "verbose_name_plural": "lotes de escrituração de NF-e",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="LoteEscrituracaoNFeNota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chave_grupo",
                    models.CharField(max_length=40, verbose_name="grupo da prévia"),
                ),
                (
                    "itens",
                    models.JSONField(
                        default=list, verbose_name="itens com natureza fixada"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("efetivada", "Efetivada pelo lote"),
                            ("ja_efetivada", "Já efetivada (pulada)"),
                            ("falhou", "Falhou"),
                        ],
                        default="pendente",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="motivo (quando falhou)",
                    ),
                ),
                (
                    "processada_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="processada em"
                    ),
                ),
                (
                    "escrituracao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="fiscal.escrituracaonfe",
                        verbose_name="escrituração",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas",
                        to="fiscal.loteescrituracaonfe",
                        verbose_name="lote",
                    ),
                ),
                (
                    "vinculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notas_de_lote_nfe",
                        to="fiscal.vinculonfeempresa",
                        verbose_name="vínculo de NF-e com empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "nota de lote de escrituração de NF-e",
                "verbose_name_plural": "notas de lote de escrituração de NF-e",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="loteescrituracaonfe",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "em_andamento")),
                fields=("empresa", "competencia"),
                name="lote_nfe_em_andamento_unico_por_mes",
            ),
        ),
        migrations.AddConstraint(
            model_name="loteescrituracaonfe",
            constraint=models.CheckConstraint(
                condition=models.Q(("estado__in", ["em_andamento", "concluido"])),
                name="lote_nfe_estado_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="loteescrituracaonfe",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("concluido_em__isnull", True), ("estado", "em_andamento")
                    ),
                    models.Q(("concluido_em__isnull", False), ("estado", "concluido")),
                    _connector="OR",
                ),
                name="lote_nfe_concluido_tem_data",
            ),
        ),
        migrations.AddConstraint(
            model_name="loteescrituracaonfenota",
            constraint=models.UniqueConstraint(
                fields=("lote", "vinculo"), name="lote_nfe_nota_unica_por_lote"
            ),
        ),
        migrations.AddConstraint(
            model_name="loteescrituracaonfenota",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("estado__in", ["pendente", "efetivada", "ja_efetivada", "falhou"])
                ),
                name="lote_nfe_nota_estado_valido",
            ),
        ),
    ]
