# Generated by Django 6.1.1 on 2026-09-11 22:08

import apps.empresas.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[apps.empresas.validators.validar_cnpj], verbose_name='CNPJ')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='tenancy.escritorio', verbose_name='escritório')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoRegimeTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(choices=[('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real')], max_length=20, verbose_name='regime tributário')),
                ('vigencia_inicio', models.DateField(verbose_name='vigência (início)')),
                ('vigencia_fim', models.DateField(blank=True, null=True, verbose_name='vigência (fim)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_regime_tributario', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'histórico de regime tributário',
                'verbose_name_plural': 'históricos de regime tributário',
                'ordering': ['-vigencia_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('matriz', 'Matriz'), ('filial', 'Filial')], max_length=10, verbose_name='tipo')),
                ('nome', models.CharField(max_length=200, verbose_name='nome/apelido')),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[apps.empresas.validators.validar_cnpj], verbose_name='CNPJ')),
                ('logradouro', models.CharField(blank=True, max_length=200, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='município')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=8, verbose_name='CEP')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimentos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'estabelecimento',
                'verbose_name_plural': 'estabelecimentos',
                'ordering': ['empresa', 'tipo'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('tipo', 'matriz')), fields=('empresa',), name='uma_matriz_por_empresa')],
            },
        ),
    ]
