# Generated by Django 6.1.1 on 2026-09-12 14:51

import apps.empresas.fields
import apps.empresas.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="cnpj",
            field=apps.empresas.fields.CNPJModelField(
                max_length=14,
                unique=True,
                validators=[apps.empresas.validators.validar_cnpj],
                verbose_name="CNPJ",
            ),
        ),
        migrations.AlterField(
            model_name="estabelecimento",
            name="cnpj",
            field=apps.empresas.fields.CNPJModelField(
                max_length=14,
                unique=True,
                validators=[apps.empresas.validators.validar_cnpj],
                verbose_name="CNPJ",
            ),
        ),
        migrations.AddConstraint(
            model_name="empresa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cnpj", django.db.models.functions.text.Upper("cnpj")),
                    models.Q(("cnpj__regex", "[^A-Z0-9]"), _negated=True),
                ),
                name="empresa_cnpj_canonico",
            ),
        ),
        migrations.AddConstraint(
            model_name="estabelecimento",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cnpj", django.db.models.functions.text.Upper("cnpj")),
                    models.Q(("cnpj__regex", "[^A-Z0-9]"), _negated=True),
                ),
                name="estabelecimento_cnpj_canonico",
            ),
        ),
    ]
