# Generated by Django 6.1.1 on 2026-09-15 02:22

import apps.empresas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_alter_empresa_cnpj_alter_estabelecimento_cnpj_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicoregimetributario",
            name="vigencia_inicio",
            field=models.DateField(
                validators=[apps.empresas.validators.validar_vigencia_de_regime],
                verbose_name="vigência (início)",
            ),
        ),
    ]
