# Generated by Django 6.1.1 on 2026-09-16 11:12
#
# DL-023, critério 1 (BL-211/A2) — avaliação de risco e plano de recuperação
# (AGENTS.md, seção 12):
#
# Risco: `AddConstraint` de uma `UniqueConstraint` condicional falha na
# aplicação se já existirem, hoje, duas ou mais linhas de
# `HistoricoRegimeTributario` com a MESMA empresa e `vigencia_fim IS NULL`
# (dois períodos "abertos" simultâneos — exatamente o estado que o achado
# BL-211/A2 mediu ser possível pelo admin). Não há dado real de cliente em
# produção nesta etapa (é bloqueador de IMPLANTAÇÃO, por isso vem antes de
# qualquer módulo novo); em ambiente de teste/homologação com esse estado
# pré-existente, a migração recusa aplicar e informa a linha em conflito —
# não corrompe dado nenhum.
#
# Reversão: `RemoveConstraint` (a reversa automática que o Django gera para
# `AddConstraint`) é segura e não perde dado — reabre a possibilidade de
# dois períodos abertos, mas não apaga nenhuma linha.
#
# Recuperação se a aplicação falhar por dado pré-existente: identificar as
# empresas com mais de um período aberto
# (`HistoricoRegimeTributario.objects.filter(vigencia_fim__isnull=True)
# .values("empresa").annotate(n=Count("id")).filter(n__gt=1)`), decidir com
# o escritório qual período é o vigente de fato e fechar manualmente a
# `vigencia_fim` dos demais antes de reaplicar esta migração — nunca apagar
# silenciosamente.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0003_alter_historicoregimetributario_vigencia_inicio"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="historicoregimetributario",
            constraint=models.UniqueConstraint(
                condition=models.Q(("vigencia_fim__isnull", True)),
                fields=("empresa",),
                name="um_periodo_de_regime_aberto_por_empresa",
            ),
        ),
    ]
