# Generated by Django 6.1.1 on 2026-09-16 12:20
#
# BL-251 (achado P7, auditoria DL-023 rodada 1): só altera `Meta.ordering`
# (`AlterModelOptions`) — não toca no esquema do banco, não bloqueia
# tabela, não tem dado a migrar. Reversão: `AlterModelOptions` reversa
# automática do Django, sem risco.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0004_um_periodo_de_regime_aberto_por_empresa"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicoregimetributario",
            options={
                "ordering": ["-vigencia_inicio", "-id"],
                "verbose_name": "histórico de regime tributário",
                "verbose_name_plural": "históricos de regime tributário",
            },
        ),
    ]
