# Generated by Django 6.1.1 on 2026-09-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_desempate_no_ordering_do_regime_tributario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nire',
            field=models.CharField(blank=True, default='', help_text='Número de Inscrição no Registro de Empresas. Opcional: empresa sem NIRE imprime o marcador `(não informado)` no cabeçalho do relatório (DL-027, RC-93).', max_length=14, verbose_name='NIRE'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nivel_de_arredondamento',
            field=models.CharField(blank=True, default='2 casas decimais (ABNT NBR 5891)', help_text='Texto que sai no cabeçalho do relatório de demonstração (NBC TG 26 item 51e). Default segue a política monetária ABNT NBR 5891 (DE-010).', max_length=100, verbose_name='nível de arredondamento'),
        ),
    ]
