# Generated by Django 6.1.1 on 2026-09-25 19:50
#
# DL-010, etapa BL-54 (pré-requisito de nível 1 — dinheiro/isolamento — para
# a recepção de NFS-e). Fortalece as CheckConstraint `empresa_cnpj_canonico`
# e `estabelecimento_cnpj_canonico`: além de exigir CNPJ canônico (maiúsculo,
# só A-Z0-9 — condição já existente), agora também exigem o FORMATO oficial
# do Anexo I da NT 2025.001 (14 caracteres, com os 2 últimos sempre
# numéricos). Django trata alteração de `condition` como remove+add da
# mesma constraint nomeada; os nomes continuam os mesmos porque
# `apps.core.restricoes` depende deles para traduzir a violação em erro 400.
# Ver o comentário de `_CNPJ_TEM_FORMATO_VALIDO` em apps/empresas/models.py:
# esta constraint confere FORMATO, não o dígito verificador (regra de
# negócio, em `apps.empresas.validators.validar_cnpj`).

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0006_empresa_nire_empresa_nivel_de_arredondamento"),
        ("tenancy", "0003_escritorio_endereco_no_timbre_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="empresa",
            name="empresa_cnpj_canonico",
        ),
        migrations.RemoveConstraint(
            model_name="estabelecimento",
            name="estabelecimento_cnpj_canonico",
        ),
        migrations.AddConstraint(
            model_name="empresa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cnpj", django.db.models.functions.text.Upper("cnpj")),
                    models.Q(("cnpj__regex", "[^A-Z0-9]"), _negated=True),
                    ("cnpj__regex", "^[A-Z0-9]{12}[0-9]{2}$"),
                ),
                name="empresa_cnpj_canonico",
            ),
        ),
        migrations.AddConstraint(
            model_name="estabelecimento",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cnpj", django.db.models.functions.text.Upper("cnpj")),
                    models.Q(("cnpj__regex", "[^A-Z0-9]"), _negated=True),
                    ("cnpj__regex", "^[A-Z0-9]{12}[0-9]{2}$"),
                ),
                name="estabelecimento_cnpj_canonico",
            ),
        ),
    ]
