# Generated by Django 6.1.1 on 2026-09-25 20:48
#
# DL-038 — cliente pessoa física no cadastro de empresas (DE-075, R1-R4).
# Migração ADITIVA: dois campos novos (`tipo_inscricao`, `modo_escrituracao`)
# com `default` — toda empresa existente vira CNPJ + contabilidade, sem
# alterar nenhum dado (critério 1 do plano). `cnpj` ganha `default=""` (só
# efeito para gravação futura de empresa CPF pela API; nenhuma empresa
# existente tem `cnpj` vazio hoje, então nada muda para elas — e o campo
# continua obrigatório em FORMULÁRIO, sem `blank=True`, ver o comentário
# em `apps/empresas/models.py`). O índice implícito de `unique=True` do
# `cnpj` é substituído por `empresa_cnpj_unico` (UniqueConstraint
# condicional) — mesma unicidade GLOBAL de sempre (PE-21), só que agora
# ignora o valor vazio (empresa CPF). Reversível: `migrate empresas 0007`
# desfaz tudo, e só é seguro enquanto não houver empresa CPF cadastrada
# (ver "Riscos e reversão" do plano) — com dado real, a correção é
# progressiva (nova migração), nunca reversão direta.
import apps.empresas.fields
import apps.empresas.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0007_bl54_cnpj_check_constraint_formato"),
        ("tenancy", "0003_escritorio_endereco_no_timbre_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="empresa",
            name="empresa_cnpj_canonico",
        ),
        migrations.AddField(
            model_name="empresa",
            name="cpf",
            field=apps.empresas.fields.CPFModelField(
                blank=True,
                default="",
                max_length=11,
                validators=[apps.empresas.validators.validar_cpf],
                verbose_name="CPF",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="modo_escrituracao",
            field=models.CharField(
                choices=[
                    ("contabilidade", "Contabilidade (partidas dobradas)"),
                    ("livro_caixa", "Livro-caixa"),
                ],
                default="contabilidade",
                max_length=20,
                verbose_name="modo de escrituração",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="tipo_inscricao",
            field=models.CharField(
                choices=[("CNPJ", "CNPJ"), ("CPF", "CPF")],
                default="CNPJ",
                max_length=4,
                verbose_name="tipo de inscrição",
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="cnpj",
            field=apps.empresas.fields.CNPJModelField(
                default="",
                max_length=14,
                validators=[apps.empresas.validators.validar_cnpj],
                verbose_name="CNPJ",
            ),
        ),
        migrations.AddConstraint(
            model_name="empresa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        models.Q(("tipo_inscricao", "CPF"), _negated=True),
                        ("cnpj", django.db.models.functions.text.Upper("cnpj")),
                        models.Q(("cnpj__regex", "[^A-Z0-9]"), _negated=True),
                        ("cnpj__regex", "^[A-Z0-9]{12}[0-9]{2}$"),
                    ),
                    ("tipo_inscricao", "CPF"),
                    _connector="OR",
                ),
                name="empresa_cnpj_canonico",
            ),
        ),
        migrations.AddConstraint(
            model_name="empresa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("tipo_inscricao", "CPF"), ("cpf__regex", "^[0-9]{11}$")),
                    models.Q(("tipo_inscricao", "CPF"), _negated=True),
                    _connector="OR",
                ),
                name="empresa_cpf_formato_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="empresa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("tipo_inscricao", "CNPJ"),
                        models.Q(("cnpj", ""), _negated=True),
                        ("cpf", ""),
                    ),
                    models.Q(
                        ("tipo_inscricao", "CPF"),
                        ("cnpj", ""),
                        models.Q(("cpf", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="empresa_inscricao_consistente_com_tipo",
            ),
        ),
        migrations.AddConstraint(
            model_name="empresa",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cnpj", ""), _negated=True),
                fields=("cnpj",),
                name="empresa_cnpj_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="empresa",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cpf", ""), _negated=True),
                fields=("cpf",),
                name="empresa_cpf_unico",
            ),
        ),
    ]
