# Generated by Django 6.1.1 on 2026-09-25 23:40
#
# Achado B8 da auditoria rodada 1 (DL-038): `modo_escrituracao` não tinha
# restrição de domínio no banco — só `choices=` no campo (validação de
# form/serializer, nunca alcança ORM direto/bulk_create/shell). Migração
# ADITIVA (só `AddConstraint`) e REVERSÍVEL (`migrate empresas 0008`
# remove a constraint sem tocar em dado nenhum). Risco de falhar em banco
# com dado real: BAIXO — nenhum caminho de escrita deste sistema grava
# `modo_escrituracao` fora de `{"contabilidade", "livro_caixa"}` (o campo
# só é setado pelo `default=` do modelo ou pelos dois valores do enum
# `ModoEscrituracao`); a migração só falharia se um valor fora do domínio
# já tivesse entrado por um caminho fora do ORM (import direto de SQL,
# por exemplo) — nesse caso, a falha da migração é o comportamento
# CORRETO (avisar antes de reforçar uma invariante que já foi violada,
# não silenciar).
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0008_dl038_cliente_pessoa_fisica"),
        ("tenancy", "0003_escritorio_endereco_no_timbre_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="empresa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("modo_escrituracao__in", ["contabilidade", "livro_caixa"])
                ),
                name="empresa_modo_escrituracao_valido",
            ),
        ),
    ]
