# Generated by hand a partir do esqueleto de `manage.py makemigrations
# empresas` (Django 6.1.1), reestruturado em passos seguros para dado
# existente — DL-041 (RC-115/DE-077, decisão do Fred na PE-68), critérios
# 1, 2 e 5 do plano.
#
# ANTES desta etapa, CNPJ e CPF de `Empresa` eram únicos no SISTEMA
# INTEIRO (DL-038, R3/PE-21) — um escritório que tentasse cadastrar um
# CNPJ/CPF já cliente de OUTRO escritório recebia "já existe", revelando
# a carteira do concorrente (e, com CPF, dado pessoal — LGPD). O Fred
# decidiu (PE-68, RC-115): a unicidade passa a ser POR ESCRITÓRIO. A MESMA
# empresa pode existir em dois escritórios — o caso normal de cliente que
# troca de contador (consequência aceita, DE-077).
#
# QUATRO mudanças, nesta ordem (cada uma comentada no ponto):
#
# 1. `Empresa`: as duas `UniqueConstraint` (`empresa_cnpj_unico`,
#    `empresa_cpf_unico`) são substituídas por versões que incluem
#    `escritorio` nos `fields` — `Empresa` já TINHA a coluna `escritorio`
#    desde sempre; não precisa de gatilho nem de coluna nova.
# 2. `Estabelecimento`: GANHA uma coluna `escritorio`, desnormalizada a
#    partir de `empresa.escritorio` — `Estabelecimento` NÃO tinha coluna
#    de escritório nenhuma, e uma `UniqueConstraint` não alcança um JOIN
#    com `empresas_empresa` (só enxerga colunas da PRÓPRIA tabela). Passo
#    a passo seguro para banco COM DADO (critério 5): a coluna nasce
#    `null=True`, um `UPDATE` por sub-consulta correlacionada preenche
#    TODAS as linhas existentes (SQL padrão, roda igual em PostgreSQL e
#    SQLite — nada aqui é condicionado a vendor), e só então a coluna vira
#    `NOT NULL`. Ver o comentário completo do campo em
#    `apps/empresas/models.py`.
# 3. `Estabelecimento.cnpj` perde o `unique=True` GLOBAL; entra
#    `estabelecimento_cnpj_unico_por_escritorio`, sobre `(escritorio,
#    cnpj)`.
# 4. Um GATILHO, só em PostgreSQL (condicionado por `schema_editor.
#    connection.vendor`, mesmo padrão das migrações 0010/0011 — DL-039):
#    ANTES de INSERT ou UPDATE de `empresa_id` em `empresas_estabelecimento`,
#    recalcula `escritorio_id` a partir da empresa referenciada — cobre
#    `bulk_create()`/`QuerySet.update()`/SQL direto, que `Estabelecimento.
#    save()` (camada Python, os dois bancos) não alcança. Em SQLite
#    (desenvolvimento, DE-014) só a camada Python existe — LIMITE ACEITO
#    e declarado, mesmo padrão do gatilho de B2 (DL-039): produção nunca
#    roda SQLite (`config/settings.py` recusa com `DEBUG=False`).
#
# REVERSÍVEL, com o LIMITE declarado no critério 5 do plano: a reversão
# das duas `UniqueConstraint` de `Empresa` (`RemoveConstraint` reverte
# para `AddConstraint` da versão GLOBAL, automaticamente, pelo próprio
# framework de migração) FALHA se, entre a ida e a volta, dois escritórios
# diferentes tiverem passado a ter o MESMO CNPJ ou CPF — exatamente o
# cenário que esta etapa existe para PERMITIR. Reverter depois de haver
# esse dado real não é "desfazer sem custo": é uma segunda migração de
# dado (mesmo espírito do comentário da 0008/0038). A reversão de
# `Estabelecimento` (coluna e constraint) não tem esse risco — é dado
# puramente DERIVADO, sem perda nem ambiguidade nenhuma ao remover.

import apps.empresas.fields
import apps.empresas.validators
import django.db.models.deletion
from django.db import migrations, models

# Passo 2: backfill de `escritorio_id` a partir de `empresa.escritorio_id`.
# Sub-consulta correlacionada — SQL padrão (`UPDATE ... SET col = (SELECT
# ...)`), sem sintaxe exclusiva de nenhum dos dois bancos; roda igual em
# PostgreSQL e SQLite. Sem `reverse_sql` (`noop`): a reversão da coluna em
# si (`RemoveField`, mais abaixo na cadeia de operações) já apaga o dado
# — não há nada para "desfazer" aqui isoladamente.
_BACKFILL_ESCRITORIO_SQL = """
UPDATE empresas_estabelecimento
SET escritorio_id = (
    SELECT escritorio_id
    FROM empresas_empresa
    WHERE empresas_empresa.id = empresas_estabelecimento.empresa_id
)
"""

# Passo 4: gatilho de sincronização, só em PostgreSQL. Diferente dos
# gatilhos de B2/DL-039 (que RECUSAM uma gravação inconsistente), este
# CORRIGE — sempre recalcula `NEW.escritorio_id`, nunca aceita o valor que
# vier de fora. É seguro porque `escritorio` de `Estabelecimento` não tem
# significado PRÓPRIO nenhum: é sempre, por definição, o de `empresa`.
_CRIAR_GATILHO_SQL = """
CREATE OR REPLACE FUNCTION empresas_sincronizar_escritorio_do_estabelecimento()
RETURNS trigger AS $$
BEGIN
    SELECT escritorio_id INTO NEW.escritorio_id
    FROM empresas_empresa
    WHERE id = NEW.empresa_id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_estabelecimento_sincroniza_escritorio
    BEFORE INSERT OR UPDATE OF empresa_id ON empresas_estabelecimento
    FOR EACH ROW
    EXECUTE FUNCTION empresas_sincronizar_escritorio_do_estabelecimento();
"""

_REMOVER_GATILHO_SQL = """
DROP TRIGGER IF EXISTS trg_estabelecimento_sincroniza_escritorio
    ON empresas_estabelecimento;
DROP FUNCTION IF EXISTS empresas_sincronizar_escritorio_do_estabelecimento();
"""


def _criar_gatilho(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(_CRIAR_GATILHO_SQL)


def _remover_gatilho(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(_REMOVER_GATILHO_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0011_bl533_bl534_gatilho_com_nome_e_trava"),
        ("tenancy", "0003_escritorio_endereco_no_timbre_and_more"),
    ]

    operations = [
        # --- 1. Empresa: unicidade global -> por escritório -------------
        migrations.RemoveConstraint(
            model_name="empresa",
            name="empresa_cnpj_unico",
        ),
        migrations.RemoveConstraint(
            model_name="empresa",
            name="empresa_cpf_unico",
        ),
        migrations.AddConstraint(
            model_name="empresa",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cnpj", ""), _negated=True),
                fields=("escritorio", "cnpj"),
                name="empresa_cnpj_unico_por_escritorio",
            ),
        ),
        migrations.AddConstraint(
            model_name="empresa",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cpf", ""), _negated=True),
                fields=("escritorio", "cpf"),
                name="empresa_cpf_unico_por_escritorio",
            ),
        ),
        # --- 2. Estabelecimento: nova coluna escritorio, com backfill ----
        migrations.AddField(
            model_name="estabelecimento",
            name="escritorio",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tenancy.escritorio",
                verbose_name="escritório",
            ),
        ),
        migrations.RunSQL(sql=_BACKFILL_ESCRITORIO_SQL, reverse_sql=migrations.RunSQL.noop),
        migrations.AlterField(
            model_name="estabelecimento",
            name="escritorio",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="tenancy.escritorio",
                verbose_name="escritório",
            ),
        ),
        # --- 3. Estabelecimento: unicidade de cnpj global -> por escritório
        migrations.AlterField(
            model_name="estabelecimento",
            name="cnpj",
            field=apps.empresas.fields.CNPJModelField(
                max_length=14,
                validators=[apps.empresas.validators.validar_cnpj],
                verbose_name="CNPJ",
            ),
        ),
        migrations.AddConstraint(
            model_name="estabelecimento",
            constraint=models.UniqueConstraint(
                fields=("escritorio", "cnpj"),
                name="estabelecimento_cnpj_unico_por_escritorio",
            ),
        ),
        # --- 4. Gatilho de sincronização (só PostgreSQL) -----------------
        migrations.RunPython(_criar_gatilho, _remover_gatilho),
    ]
