# Generated by Django 6.1.1 on 2026-09-26 20:47

import apps.empresas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0013_dl041_ub1_trava_de_escritorio"),
        ("tenancy", "0003_escritorio_endereco_no_timbre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="caepf",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cadastro de Atividade Econômica da Pessoa Física (opcional, RC-129) — 14 dígitos, sem máscara. Só para tipo de inscrição CPF.",
                max_length=14,
                validators=[apps.empresas.validators.validar_caepf],
                verbose_name="CAEPF",
            ),
        ),
        migrations.AddConstraint(
            model_name="empresa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("tipo_inscricao", "CPF"),
                        models.Q(
                            ("caepf", ""),
                            ("caepf__regex", "^[0-9]{14}$"),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        models.Q(("tipo_inscricao", "CPF"), _negated=True),
                        ("caepf", ""),
                    ),
                    _connector="OR",
                ),
                name="empresa_caepf_so_para_cpf_com_formato_valido",
            ),
        ),
    ]
