# Generated by Django 6.1.1 on 2026-09-27 18:50
#
# DL-046, fatia 3 (RC-127/HI-34): código de ocupação do Carnê-Leão Web no
# cadastro da pessoa física — campo aditivo, sem alterar dado existente.
# Fonte da tabela de valores válidos: `apps.empresas.validators.
# TABELA_OCUPACOES_CARNE_LEAO_WEB` (Manual do Carnê-Leão, "Códigos de
# ocupações", Receita Federal, consultado em 2026-09-27).

import apps.empresas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0014_dl046_caepf"),
        ("tenancy", "0003_escritorio_endereco_no_timbre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="codigo_ocupacao",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código de 3 dígitos da tabela oficial de ocupações do Carnê-Leão Web (RC-127/HI-34). Só para tipo de inscrição CPF. Pode ser sobreposto por conta do livro-caixa.",
                max_length=3,
                validators=[apps.empresas.validators.validar_codigo_ocupacao],
                verbose_name="código de ocupação (Carnê-Leão Web)",
            ),
        ),
        migrations.AddConstraint(
            model_name="empresa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("tipo_inscricao", "CPF"),
                        models.Q(
                            ("codigo_ocupacao", ""),
                            ("codigo_ocupacao__regex", "^[0-9]{3}$"),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        models.Q(("tipo_inscricao", "CPF"), _negated=True),
                        ("codigo_ocupacao", ""),
                    ),
                    _connector="OR",
                ),
                name="empresa_codigo_ocupacao_so_para_cpf_com_formato_valido",
            ),
        ),
    ]
