# Generated by Django 6.1.2 on 2026-10-08 04:40

import apps.empresas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0015_dl046_fatia3_codigo_ocupacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="data_abertura_cnpj",
            field=models.DateField(
                blank=True,
                help_text="Data de abertura constante do CNPJ. Obrigatória para apurar o RBT12 do Simples Nacional (DL-074).",
                null=True,
                validators=[apps.empresas.models.validar_data_abertura_nao_futura],
                verbose_name="data de abertura no CNPJ",
            ),
        ),
    ]
