# Generated by Django 6.1.1 on 2026-09-11 22:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='código')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('ativo', 'Ativo'), ('passivo', 'Passivo'), ('patrimonio_liquido', 'Patrimônio Líquido'), ('receita', 'Receita'), ('despesa', 'Despesa')], max_length=20, verbose_name='tipo')),
                ('natureza', models.CharField(choices=[('devedora', 'Devedora'), ('credora', 'Credora')], max_length=10, verbose_name='natureza')),
                ('aceita_lancamento', models.BooleanField(default=True, help_text='Contas sintéticas (agrupadoras) não devem receber lançamento direto.', verbose_name='aceita lançamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('conta_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcontas', to='contabilidade.conta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'conta',
                'verbose_name_plural': 'contas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('historico', models.CharField(max_length=300, verbose_name='histórico')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='empresas.empresa')),
                ('estorno_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estornos', to='contabilidade.lancamentocontabil')),
            ],
            options={
                'verbose_name': 'lançamento contábil',
                'verbose_name_plural': 'lançamentos contábeis',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=10, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_lancamento', to='contabilidade.conta')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contabilidade.lancamentocontabil')),
            ],
            options={
                'verbose_name': 'item de lançamento',
                'verbose_name_plural': 'itens de lançamento',
            },
        ),
        migrations.AddConstraint(
            model_name='conta',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='codigo_unico_por_empresa'),
        ),
    ]
