# Generated by Django 6.1.1 on 2026-09-12 02:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidade", "0001_initial"),
        ("empresas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamentocontabil",
            name="chave_idempotencia",
            field=models.CharField(
                blank=True,
                help_text="Cabeçalho Idempotency-Key enviado pelo cliente ao criar o lançamento. Opcional: repetir o POST com a mesma chave, na mesma empresa, devolve o lançamento já criado em vez de duplicá-lo (BL-41). Não é derivada de data/histórico/itens — dois lançamentos idênticos podem ser legítimos em contabilidade.",
                max_length=255,
                null=True,
                verbose_name="chave de idempotência",
            ),
        ),
        migrations.AddField(
            model_name="lancamentocontabil",
            name="chave_idempotencia_fingerprint",
            field=models.CharField(
                blank=True,
                help_text="Hash SHA-256 (hexadecimal) do conteúdo do lançamento (data, histórico e itens) no momento em que a Idempotency-Key foi usada. Permite recusar com 409 quando a MESMA chave é reaproveitada para um conteúdo DIFERENTE, em vez de devolver silenciosamente o lançamento antigo como se fosse sucesso (achado de auditoria A2 do plano DL-007 — reaproveitar a chave para outra coisa é 'corrupção por omissão', que não aparece na conciliação).",
                max_length=64,
                null=True,
                verbose_name="impressão digital da chave de idempotência",
            ),
        ),
        migrations.AddConstraint(
            model_name="lancamentocontabil",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estorno_de__isnull", False)),
                fields=("estorno_de",),
                name="estorno_de_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="lancamentocontabil",
            constraint=models.UniqueConstraint(
                condition=models.Q(("chave_idempotencia__isnull", False)),
                fields=("empresa", "chave_idempotencia"),
                name="chave_idempotencia_unica_por_empresa",
            ),
        ),
    ]
