# Generated by Django 6.1.1 on 2026-09-15 02:22

import apps.contabilidade.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidade", "0002_lancamentocontabil_chave_idempotencia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lancamentocontabil",
            name="data",
            field=models.DateField(
                validators=[
                    apps.contabilidade.validators.validar_data_de_lancamento_do_modelo
                ],
                verbose_name="data",
            ),
        ),
    ]
