# Generated by Django 6.1.1 on 2026-09-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidade", "0006_fechamento_reabertura_e_entrega_de_competencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="conta",
            name="classificacao_patrimonial",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ativo_circulante", "Ativo circulante"),
                    (
                        "ativo_nao_circulante_realizavel_a_longo_prazo",
                        "Ativo não circulante — realizável a longo prazo",
                    ),
                    (
                        "ativo_nao_circulante_investimentos",
                        "Ativo não circulante — investimentos",
                    ),
                    (
                        "ativo_nao_circulante_imobilizado",
                        "Ativo não circulante — imobilizado",
                    ),
                    (
                        "ativo_nao_circulante_intangivel",
                        "Ativo não circulante — intangível",
                    ),
                    ("passivo_circulante", "Passivo circulante"),
                    ("passivo_nao_circulante", "Passivo não circulante"),
                ],
                max_length=60,
                null=True,
                verbose_name="classificação (circulante/não circulante)",
            ),
        ),
    ]
