# Generated by Django 6.1.1 (manage.py makemigrations contabilidade), sem
# edição manual das `operations` — DL-043 (BL-474): cria a tabela de
# parâmetro contábil por empresa com vigência (molde do
# `HistoricoRegimeTributario`, DE-039). A camada 1 da não sobreposição (a
# `UniqueConstraint` condicional abaixo) já sai daqui; a camada 2 (gatilho,
# só PostgreSQL) é a migração 0009, no mesmo padrão condicionado a
# `connection.vendor` das migrações 0010–0013 de `apps.empresas`
# (DL-039/DL-041) — ver o comentário de lá para o motivo de ser uma
# migração SEPARADA, e não RunSQL dentro desta.
#
# Reversível sem ressalva: `RemoveField`/`DeleteModel` (gerados
# automaticamente pelo `migrate contabilidade 0007`) não têm o mesmo risco
# de dado real das migrações 0012/0013 de `apps.empresas` — este modelo é
# NOVO nesta etapa, não existe dado histórico para perder ao reverter.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidade", "0007_conta_classificacao_patrimonial"),
        ("empresas", "0013_dl041_ub1_trava_de_escritorio"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametroContabilEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periodicidade_zeramento",
                    models.CharField(
                        choices=[
                            ("mensal", "Mensal"),
                            ("trimestral", "Trimestral"),
                            ("anual", "Anual"),
                        ],
                        max_length=10,
                        verbose_name="periodicidade do zeramento",
                    ),
                ),
                ("vigencia_inicio", models.DateField(verbose_name="vigência (início)")),
                (
                    "vigencia_fim",
                    models.DateField(
                        blank=True, null=True, verbose_name="vigência (fim)"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "conta_lucros_acumulados",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contabilidade.conta",
                        verbose_name="conta de lucros acumulados",
                    ),
                ),
                (
                    "conta_prejuizos_acumulados",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contabilidade.conta",
                        verbose_name="conta de (-) prejuízos acumulados",
                    ),
                ),
                (
                    "conta_resultado_do_exercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contabilidade.conta",
                        verbose_name="conta de resultado do exercício",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parametros_contabeis",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "parâmetro contábil da empresa",
                "verbose_name_plural": "parâmetros contábeis da empresa",
                "ordering": ["-vigencia_inicio", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("vigencia_fim__isnull", True)),
                        fields=("empresa",),
                        name="um_periodo_de_parametro_contabil_aberto_por_empresa",
                    )
                ],
            },
        ),
    ]
