# Generated by Django 6.1.1 on 2026-09-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidade", "0009_gatilho_sem_sobreposicao_de_vigencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="conta",
            name="classificacao_dre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("receita_bruta", "Receita bruta de vendas e serviços"),
                    (
                        "deducoes_da_receita",
                        "Deduções da receita (impostos, devoluções e abatimentos)",
                    ),
                    ("custo", "Custo (CMV/CPV/CSP)"),
                    ("despesas_com_vendas", "Despesas com vendas"),
                    (
                        "despesas_gerais_e_administrativas",
                        "Despesas gerais e administrativas",
                    ),
                    ("outras_receitas", "Outras receitas"),
                    ("outras_despesas", "Outras despesas"),
                    ("outras_despesas_operacionais", "Outras despesas operacionais"),
                    (
                        "resultado_equivalencia_patrimonial",
                        "Resultado de equivalência patrimonial",
                    ),
                    ("receitas_financeiras", "Receitas financeiras"),
                    ("despesas_financeiras", "Despesas financeiras"),
                    ("provisao_irpj_csll", "Provisão para IRPJ e CSLL"),
                    ("participacoes", "Participações"),
                ],
                max_length=60,
                null=True,
                verbose_name="classificação (DRE)",
            ),
        ),
    ]
