# Generated by Django 6.1.1 on 2026-09-28 15:03
#
# DL-048, etapa CTB-12 (com a CTB-13): o TERCEIRO campo de classificação
# do mesmo padrão da casa — `classificacao_patrimonial` (DL-033) e
# `classificacao_dre` (DL-045) antes deste. Conta existente nasce SEM
# classificação (`null=True`): ninguém infere linha de demonstração de
# código ou nome de conta; quem classifica é o contador, e a apuração da
# DLPA declara o que falta em vez de presumir.
#
# Sem migração de DADO (só AddField nulo): nenhuma conta é classificada
# automaticamente. A `CheckConstraint` é a defesa de BANCO (DE-008,
# camada 1) contra `classificacao_dlpa=""` gravado por fora do
# `full_clean()` — o mesmo estado torto que a migração 0011 só CORRIGIU
# na DRE depois de existir; aqui ele nunca chega a existir.
#
# 29/09/2026: as `choices` saíram com ONZE valores, sem "correção
# monetária do saldo inicial" (decisão do Fred; Lei 9.249/95, art. 4º,
# p.ú.). Esta migração é corrigida no lugar — e não por uma 0013 — porque
# ela NUNCA entrou na `main` e portanto não foi aplicada em ambiente
# compartilhado nenhum; corrigir aqui evita gravar uma etapa de migração
# para desfazer algo que só existiu em branch.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0011_dl045_rodada1_classificacao_dre_nao_vazia'),
        ('empresas', '0015_dl046_fatia3_codigo_ocupacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='classificacao_dlpa',
            field=models.CharField(blank=True, choices=[('lucros_ou_prejuizos_acumulados', 'Lucros ou prejuízos acumulados (conta da DLPA)'), ('resultado_do_exercicio', 'Resultado do exercício (lucro ou prejuízo transferido)'), ('reserva_legal', 'Reserva legal'), ('reserva_estatutaria', 'Reserva estatutária'), ('reserva_para_contingencias', 'Reserva para contingências'), ('reserva_de_incentivos_fiscais', 'Reserva de incentivos fiscais'), ('reserva_de_retencao_de_lucros', 'Reserva de retenção de lucros'), ('reserva_de_lucros_a_realizar', 'Reserva de lucros a realizar'), ('dividendo', 'Dividendos distribuídos'), ('lucro_incorporado_ao_capital', 'Lucro incorporado ao capital'), ('ajuste_de_exercicio_anterior', 'Ajuste de exercício anterior')], max_length=60, null=True, verbose_name='classificação (DLPA)'),
        ),
        migrations.AddConstraint(
            model_name='conta',
            constraint=models.CheckConstraint(condition=models.Q(('classificacao_dlpa', ''), _negated=True), name='ck_conta_classificacao_dlpa_nao_vazia'),
        ),
    ]
