# Generated by Django 6.1.1 on 2026-10-01 10:57
#
# DL-061 (CTB-14, DMPL), fatia 1. Risco da migração: BAIXO. Três operações
# aditivas, nenhuma reescreve dado:
#
# - `Conta.classificacao_dmpl`: AddField NULO (conta existente nasce SEM
#   coluna; ninguém infere coluna de código ou nome — a apuração declara o
#   que falta). Sem migração de dado.
# - `ParametroContabilEmpresa.adota_nbc_tg_51_antecipadamente`: AddField
#   booleano com default `False` — toda vigência existente continua citando
#   a norma que valia antes (NBC TG 26 R5) até 01/01/2027.
# - `ck_conta_classificacao_dmpl_nao_vazia`: defesa de banco contra `""`. O
#   campo acabou de nascer, então nenhuma linha existente a viola.
#
# Recuperação: `migrate contabilidade 0017` remove as duas colunas e a
# constraint. A reversão PERDE as classificações de coluna e a marca de
# adoção antecipada gravadas depois desta migração (a trilha de auditoria
# registra cada mudança, mas só a partir de quando existe).

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidade", "0017_dl052_r1_backfill_so_na_mesma_empresa"),
        ("empresas", "0015_dl046_fatia3_codigo_ocupacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="conta",
            name="classificacao_dmpl",
            field=models.CharField(
                blank=True,
                choices=[
                    ("capital_social", "Capital social"),
                    ("agio_na_emissao_de_acoes", "Ágio na emissão de ações"),
                    (
                        "alienacao_de_partes_beneficiarias_e_bonus_de_subscricao",
                        "Alienação de partes beneficiárias e bônus de subscrição",
                    ),
                    (
                        "ajustes_de_avaliacao_patrimonial",
                        "Ajustes de avaliação patrimonial",
                    ),
                    ("reserva_legal", "Reserva legal"),
                    ("reserva_estatutaria", "Reserva estatutária"),
                    ("reserva_para_contingencias", "Reserva para contingências"),
                    ("reserva_de_incentivos_fiscais", "Reserva de incentivos fiscais"),
                    ("reserva_de_retencao_de_lucros", "Reserva de retenção de lucros"),
                    ("reserva_de_lucros_a_realizar", "Reserva de lucros a realizar"),
                    ("acoes_ou_quotas_em_tesouraria", "Ações ou quotas em tesouraria"),
                    (
                        "lucros_ou_prejuizos_acumulados",
                        "Lucros ou prejuízos acumulados",
                    ),
                ],
                max_length=60,
                null=True,
                verbose_name="classificação (coluna da DMPL)",
            ),
        ),
        migrations.AddField(
            model_name="parametrocontabilempresa",
            name="adota_nbc_tg_51_antecipadamente",
            field=models.BooleanField(
                default=False, verbose_name="adota a NBC TG 51 antecipadamente"
            ),
        ),
        migrations.AddConstraint(
            model_name="conta",
            constraint=models.CheckConstraint(
                condition=models.Q(("classificacao_dmpl", ""), _negated=True),
                name="ck_conta_classificacao_dmpl_nao_vazia",
            ),
        ),
    ]
