# DL-061, etapa 2 (BL-603, RC-153): as novas linhas/colunas
# "dividendo_adicional proposto" — `ClassificacaoDlpa.DIVIDENDO_ADICIONAL_
# PROPOSTO` e `ClassificacaoDmpl.DIVIDENDO_ADICIONAL_PROPOSTO`. A migração é
# só de `choices` (AlterField): nenhum dado muda e nada é regravado — a
# conta do cliente continua com a classificação que tiver; classificá-la é
# ato do contador, com trilha. Por isso vale para banco vazio e para base
# anterior sem etapa de dados.
# Generated by Django 6.1.1 on 2026-10-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidade", "0018_dl061_coluna_da_dmpl_e_adocao_antecipada_tg51"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conta",
            name="classificacao_dlpa",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "lucros_ou_prejuizos_acumulados",
                        "Lucros ou prejuízos acumulados (conta da DLPA)",
                    ),
                    (
                        "resultado_do_exercicio",
                        "Resultado do exercício (lucro ou prejuízo transferido)",
                    ),
                    ("reserva_legal", "Reserva legal"),
                    ("reserva_estatutaria", "Reserva estatutária"),
                    ("reserva_para_contingencias", "Reserva para contingências"),
                    ("reserva_de_incentivos_fiscais", "Reserva de incentivos fiscais"),
                    ("reserva_de_retencao_de_lucros", "Reserva de retenção de lucros"),
                    ("reserva_de_lucros_a_realizar", "Reserva de lucros a realizar"),
                    ("dividendo", "Dividendos distribuídos"),
                    ("dividendo_adicional_proposto", "Dividendo adicional proposto"),
                    ("lucro_incorporado_ao_capital", "Lucro incorporado ao capital"),
                    ("ajuste_de_exercicio_anterior", "Ajuste de exercício anterior"),
                ],
                max_length=60,
                null=True,
                verbose_name="classificação (DLPA)",
            ),
        ),
        migrations.AlterField(
            model_name="conta",
            name="classificacao_dmpl",
            field=models.CharField(
                blank=True,
                choices=[
                    ("capital_social", "Capital social"),
                    ("agio_na_emissao_de_acoes", "Ágio na emissão de ações"),
                    (
                        "alienacao_de_partes_beneficiarias_e_bonus_de_subscricao",
                        "Alienação de partes beneficiárias e bônus de subscrição",
                    ),
                    ("ajustes_de_avaliacao_patrimonial", "Ajustes de avaliação patrimonial"),
                    ("reserva_legal", "Reserva legal"),
                    ("reserva_estatutaria", "Reserva estatutária"),
                    ("reserva_para_contingencias", "Reserva para contingências"),
                    ("reserva_de_incentivos_fiscais", "Reserva de incentivos fiscais"),
                    ("reserva_de_retencao_de_lucros", "Reserva de retenção de lucros"),
                    ("reserva_de_lucros_a_realizar", "Reserva de lucros a realizar"),
                    ("acoes_ou_quotas_em_tesouraria", "Ações ou quotas em tesouraria"),
                    ("lucros_ou_prejuizos_acumulados", "Lucros ou prejuízos acumulados"),
                    ("dividendo_adicional_proposto", "Dividendo adicional proposto"),
                ],
                max_length=60,
                null=True,
                verbose_name="classificação (coluna da DMPL)",
            ),
        ),
    ]
