# Generated by Django 6.1.1 on 2026-10-01 15:11
#
# DL-062 (G1, RC-153), DMPL: coluna "dividendo adicional proposto". Risco da
# migração: BAIXO. Uma única operação, só de metadados: `AlterField` que
# acrescenta uma opção a `choices` de `Conta.classificacao_dmpl`. Choices do
# Django não viram constraint de banco (a tabela não muda), nenhuma linha é
# reescrita e nenhuma classificação existente é tocada.
#
# Recuperação: `migrate contabilidade 0018` é inofensiva para o esquema. Conta
# que já tenha sido classificada na coluna nova continua gravada com o valor
# (o banco não o recusa); a apuração a acusaria como "coluna desconhecida" até
# a conta ser reclassificada, e a trilha de auditoria registra a mudança.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidade", "0018_dl061_coluna_da_dmpl_e_adocao_antecipada_tg51"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conta",
            name="classificacao_dmpl",
            field=models.CharField(
                blank=True,
                choices=[
                    ("capital_social", "Capital social"),
                    ("agio_na_emissao_de_acoes", "Ágio na emissão de ações"),
                    (
                        "alienacao_de_partes_beneficiarias_e_bonus_de_subscricao",
                        "Alienação de partes beneficiárias e bônus de subscrição",
                    ),
                    (
                        "ajustes_de_avaliacao_patrimonial",
                        "Ajustes de avaliação patrimonial",
                    ),
                    ("reserva_legal", "Reserva legal"),
                    ("reserva_estatutaria", "Reserva estatutária"),
                    ("reserva_para_contingencias", "Reserva para contingências"),
                    ("reserva_de_incentivos_fiscais", "Reserva de incentivos fiscais"),
                    ("reserva_de_retencao_de_lucros", "Reserva de retenção de lucros"),
                    ("reserva_de_lucros_a_realizar", "Reserva de lucros a realizar"),
                    ("acoes_ou_quotas_em_tesouraria", "Ações ou quotas em tesouraria"),
                    (
                        "lucros_ou_prejuizos_acumulados",
                        "Lucros ou prejuízos acumulados",
                    ),
                    ("dividendo_adicional_proposto", "Dividendo adicional proposto"),
                ],
                max_length=60,
                null=True,
                verbose_name="classificação (coluna da DMPL)",
            ),
        ),
    ]
