# Generated by Django 6.1.1 on 2026-10-03 20:51
#
# DL-061, fatia 2 (BL-605): `MarcacaoDmpl`, a marcação manual de um
# lançamento numa célula (linha × coluna) da DMPL (decisões E15–E17 do
# plano). POR QUE existe: a regra automática de linha não decide alguns
# eventos (lançamento ambíguo, par sem regra, contrapartida sem linha) e a
# emissão ficava vetada sem saída — a marcação é a exceção prevista pela
# RC-151, guardada FORA do livro para o lançamento efetivado continuar
# imutável. As duas restrições são a defesa de banco do contrato do
# conjunto: linha × coluna única por lançamento (a duplicata seria ambígua
# na soma por coluna) e `valor != 0` (marcação não descreve evento zero);
# ambas são validadas ANTES do INSERT pelo serviço
# (`salvar_marcacoes_da_dmpl`) — ver `apps/core/restricoes.py`.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidade", "0019_dl061_etapa2_dividendo_adicional_proposto"),
        ("empresas", "0015_dl046_fatia3_codigo_ocupacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarcacaoDmpl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("linha", models.CharField(max_length=60, verbose_name="linha da DMPL")),
                (
                    "coluna",
                    models.CharField(
                        choices=[
                            ("capital_social", "Capital social"),
                            ("agio_na_emissao_de_acoes", "Ágio na emissão de ações"),
                            (
                                "alienacao_de_partes_beneficiarias_e_bonus_de_subscricao",
                                "Alienação de partes beneficiárias e bônus de subscrição",
                            ),
                            (
                                "ajustes_de_avaliacao_patrimonial",
                                "Ajustes de avaliação patrimonial",
                            ),
                            ("reserva_legal", "Reserva legal"),
                            ("reserva_estatutaria", "Reserva estatutária"),
                            ("reserva_para_contingencias", "Reserva para contingências"),
                            ("reserva_de_incentivos_fiscais", "Reserva de incentivos fiscais"),
                            ("reserva_de_retencao_de_lucros", "Reserva de retenção de lucros"),
                            ("reserva_de_lucros_a_realizar", "Reserva de lucros a realizar"),
                            ("acoes_ou_quotas_em_tesouraria", "Ações ou quotas em tesouraria"),
                            ("lucros_ou_prejuizos_acumulados", "Lucros ou prejuízos acumulados"),
                            ("dividendo_adicional_proposto", "Dividendo adicional proposto"),
                        ],
                        max_length=60,
                        verbose_name="coluna da DMPL",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(decimal_places=2, max_digits=18, verbose_name="valor"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marcacoes_dmpl",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "lancamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marcacoes_dmpl",
                        to="contabilidade.lancamentocontabil",
                    ),
                ),
            ],
            options={
                "verbose_name": "marcação da DMPL",
                "verbose_name_plural": "marcações da DMPL",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lancamento", "linha", "coluna"),
                        name="marcacao_dmpl_unica_por_linha_e_coluna",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("valor", 0), _negated=True),
                        name="ck_marcacaodmpl_valor_diferente_de_zero",
                    ),
                ],
            },
        ),
    ]
