# Generated by Django 6.1.1 on 2026-10-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0020_dl061_bl605_marcacao_dmpl'),
        ('empresas', '0015_dl046_fatia3_codigo_ocupacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='caixa_e_equivalentes',
            field=models.BooleanField(default=False, help_text='Entra na conciliação do item 45 do CPC 03 (R2) e é o lado CAIXA dos lançamentos na apuração da DFC. Equivalente de caixa é aplicação de curto prazo, em regra vencimento de três meses ou menos (item 7) — o padrão fica a cargo do escritório, não do produto, e por isso não há marcação automática.', verbose_name='caixa e equivalente de caixa'),
        ),
        migrations.AddField(
            model_name='conta',
            name='classificacao_dfc',
            field=models.CharField(blank=True, choices=[('operacional', 'Operacional'), ('investimento', 'Investimento'), ('financiamento', 'Financiamento')], help_text='CPC 03 (R2), itens 10 e 13 a 17: em qual das três atividades o movimento desta conta entra na DFC. Vazio quando a conta ainda não foi classificada — e a apuração veta enquanto houver conta movimentada sem classificação.', max_length=60, null=True, verbose_name='atividade do fluxo de caixa'),
        ),
        migrations.AddField(
            model_name='conta',
            name='item_de_resultado_sem_caixa',
            field=models.BooleanField(default=False, help_text='CPC 03 (R2), item 20(b): depreciação, amortização, provisões e semelhantes entram no ajuste do método indireto e não como fluxo. Só vale para conta de resultado.', verbose_name='item de resultado que não movimenta caixa'),
        ),
        migrations.AddConstraint(
            model_name='conta',
            constraint=models.CheckConstraint(condition=models.Q(('classificacao_dfc', ''), _negated=True), name='ck_conta_classificacao_dfc_nao_vazia'),
        ),
    ]
