# Generated by Django 6.1.1 on 2026-10-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0021_conta_caixa_e_equivalentes_conta_classificacao_dfc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='item_de_resultado_sem_caixa',
            field=models.BooleanField(default=False, help_text='CPC 03 (R2), item 20(b): depreciação, amortização e semelhantes entram no ajuste do método indireto e não como fluxo. Só vale para conta de resultado. Para PROVISÃO operacional, não use esta marcação: marque a contrapartida (o passivo) como atividade operacional — marcar as duas ajusta o mesmo fato duas vezes e a conciliação do item 20A veta a DFC.', verbose_name='item de resultado que não movimenta caixa'),
        ),
    ]
