# Generated by Django 6.1.2 on 2026-10-08 14:29

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# DL-077, fatia 3 (frente A) — gatilhos de imutabilidade da importação de lançamentos.
#
# POR QUÊ. A importação é a área de conferência: depois de efetivada ou descartada, nenhuma
# linha dela pode mudar, porque é a trilha do que entrou no Diário. O `save()` do modelo
# recusa, mas um `QuerySet.update()` ou SQL direto passaria. Mesmo padrão das migrações 0013
# e 0023 de `contabilidade`: gatilho BEFORE, RAISE EXCEPTION com CONSTRAINT nomeado (o mapa de
# `apps/core/restricoes.py` traduz pelo nome), RunPython que só emite SQL no PostgreSQL.
#
# O QUE FAZ.
# 1. `contabilidade_importacaolancamentos`: UPDATE e DELETE só com estado 'em_conferencia';
#    DELETE é recusado sempre (`importacao_lancamentos_sem_exclusao`).
# 2. `contabilidade_lancamentoimportado`: INSERT, UPDATE e DELETE só com a importação pai em
#    'em_conferencia'; DELETE é recusado sempre (`lancamento_importado_sem_exclusao`).
#    A efetivação preenche `lancamento_id` ENQUANTO a importação ainda está em conferência, e
#    só depois troca o estado da importação.

_CRIAR_GATILHOS_SQL = """
CREATE OR REPLACE FUNCTION contabilidade_recusar_alteracao_de_importacao()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'importação de lançamentos não pode ser excluída; descarte-a com motivo'
            USING ERRCODE = '23514', CONSTRAINT = 'importacao_lancamentos_sem_exclusao';
    END IF;
    IF OLD.estado <> 'em_conferencia' THEN
        RAISE EXCEPTION 'importação já efetivada ou descartada não pode ser alterada'
            USING ERRCODE = '23514',
                  CONSTRAINT = 'importacao_lancamentos_imutavel_depois_de_fechada';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_importacao_lancamentos_imutavel
    ON contabilidade_importacaolancamentos;
CREATE TRIGGER trg_importacao_lancamentos_imutavel
    BEFORE UPDATE OR DELETE ON contabilidade_importacaolancamentos
    FOR EACH ROW EXECUTE FUNCTION contabilidade_recusar_alteracao_de_importacao();

CREATE OR REPLACE FUNCTION contabilidade_recusar_linha_de_importacao()
RETURNS trigger AS $$
DECLARE
    id_da_importacao bigint;
    estado_da_importacao text;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'lançamento importado não pode ser excluído: faz parte da trilha'
            USING ERRCODE = '23514', CONSTRAINT = 'lancamento_importado_sem_exclusao';
    END IF;
    IF TG_OP = 'INSERT' THEN
        id_da_importacao := NEW.importacao_id;
    ELSE
        id_da_importacao := OLD.importacao_id;
    END IF;
    SELECT estado INTO estado_da_importacao
        FROM contabilidade_importacaolancamentos WHERE id = id_da_importacao;
    IF estado_da_importacao IS DISTINCT FROM 'em_conferencia' THEN
        RAISE EXCEPTION 'lançamento de importação já efetivada ou descartada não pode ser alterado'
            USING ERRCODE = '23514',
                  CONSTRAINT = 'lancamento_importado_imutavel_depois_de_fechada';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_lancamento_importado_imutavel ON contabilidade_lancamentoimportado;
CREATE TRIGGER trg_lancamento_importado_imutavel
    BEFORE INSERT OR UPDATE OR DELETE ON contabilidade_lancamentoimportado
    FOR EACH ROW EXECUTE FUNCTION contabilidade_recusar_linha_de_importacao();
"""

_REMOVER_GATILHOS_SQL = """
DROP TRIGGER IF EXISTS trg_lancamento_importado_imutavel ON contabilidade_lancamentoimportado;
DROP TRIGGER IF EXISTS trg_importacao_lancamentos_imutavel ON contabilidade_importacaolancamentos;
DROP FUNCTION IF EXISTS contabilidade_recusar_linha_de_importacao();
DROP FUNCTION IF EXISTS contabilidade_recusar_alteracao_de_importacao();
"""


def _criar_gatilhos(apps, schema_editor):
    # NO-OP fora do PostgreSQL: o SQLite não tem este gatilho (mesmo limite das 0013/0023).
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(_CRIAR_GATILHOS_SQL, params=None)


def _remover_gatilhos(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(_REMOVER_GATILHOS_SQL, params=None)


class Migration(migrations.Migration):
    dependencies = [
        ("contabilidade", "0023_dl069_periodo_encerrado_recusa_insert"),
        ("empresas", "0007_bl54_cnpj_check_constraint_formato"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportacaoLancamentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[
                            ("ecd", "ECD (I200/I250)"),
                            ("proprio", "DataLedger (TXT próprio)"),
                            ("excel", "Excel (.xlsx)"),
                            ("referencia", "Sistema de referência (6000/6100)"),
                        ],
                        max_length=20,
                        verbose_name="formato",
                    ),
                ),
                (
                    "nome_arquivo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="nome do arquivo",
                    ),
                ),
                (
                    "sha256",
                    models.CharField(max_length=64, verbose_name="SHA-256 do arquivo"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("em_conferencia", "Em conferência"),
                            ("efetivada", "Efetivada"),
                            ("descartada", "Descartada"),
                        ],
                        default="em_conferencia",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "politica_de_efetivacao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="política de efetivação",
                    ),
                ),
                (
                    "quantidade_lancamentos",
                    models.PositiveIntegerField(default=0, verbose_name="lançamentos lidos"),
                ),
                (
                    "quantidade_com_erro",
                    models.PositiveIntegerField(default=0, verbose_name="lançamentos com erro"),
                ),
                (
                    "quantidade_com_aviso",
                    models.PositiveIntegerField(default=0, verbose_name="lançamentos com aviso"),
                ),
                (
                    "quantidade_efetivados",
                    models.PositiveIntegerField(default=0, verbose_name="lançamentos efetivados"),
                ),
                (
                    "quantidade_nao_efetivados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="lançamentos não efetivados"
                    ),
                ),
                (
                    "soma_debitos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="soma dos débitos",
                    ),
                ),
                (
                    "soma_creditos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=18,
                        verbose_name="soma dos créditos",
                    ),
                ),
                (
                    "ocorrencias_do_arquivo",
                    models.JSONField(
                        blank=True, default=list, verbose_name="ocorrências do arquivo"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="recebido em"),
                ),
                (
                    "efetivada_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="efetivada em"),
                ),
                (
                    "descartada_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="descartada em"),
                ),
                (
                    "motivo_do_descarte",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="motivo do descarte",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recebido por",
                    ),
                ),
                (
                    "descartada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="descartada por",
                    ),
                ),
                (
                    "efetivada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="efetivada por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="importacoes_de_lancamentos",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "importação de lançamentos",
                "verbose_name_plural": "importações de lançamentos",
                "ordering": ["-criado_em", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LancamentoImportado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_origem",
                    models.CharField(max_length=100, verbose_name="número de origem"),
                ),
                ("linha", models.PositiveIntegerField(verbose_name="linha de origem")),
                ("data", models.DateField(verbose_name="data")),
                (
                    "historico",
                    models.TextField(blank=True, default="", verbose_name="histórico"),
                ),
                ("partidas", models.JSONField(default=list, verbose_name="partidas")),
                (
                    "ocorrencias",
                    models.JSONField(blank=True, default=list, verbose_name="ocorrências"),
                ),
                (
                    "tem_erro",
                    models.BooleanField(default=False, verbose_name="tem erro"),
                ),
                (
                    "tem_aviso",
                    models.BooleanField(default=False, verbose_name="tem aviso"),
                ),
                (
                    "aceito_com_aviso",
                    models.BooleanField(default=False, verbose_name="avisos aceitos"),
                ),
                (
                    "importacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lancamentos",
                        to="contabilidade.importacaolancamentos",
                    ),
                ),
                (
                    "lancamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="origem_na_importacao",
                        to="contabilidade.lancamentocontabil",
                        verbose_name="lançamento efetivado",
                    ),
                ),
            ],
            options={
                "verbose_name": "lançamento importado",
                "verbose_name_plural": "lançamentos importados",
                "ordering": ["linha", "id"],
            },
        ),
        migrations.CreateModel(
            name="DeParaConta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[
                            ("ecd", "ECD (I200/I250)"),
                            ("proprio", "DataLedger (TXT próprio)"),
                            ("excel", "Excel (.xlsx)"),
                            ("referencia", "Sistema de referência (6000/6100)"),
                        ],
                        max_length=20,
                        verbose_name="formato",
                    ),
                ),
                (
                    "codigo_origem",
                    models.CharField(max_length=100, verbose_name="código de origem"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="definido em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "conta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="de_para_de_importacao",
                        to="contabilidade.conta",
                        verbose_name="conta",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="definido por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="de_para_de_contas_de_importacao",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "de-para de conta (importação)",
                "verbose_name_plural": "de-para de contas (importação)",
                "ordering": ["formato", "codigo_origem"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "formato", "codigo_origem"),
                        name="depara_conta_unica_por_empresa_formato_origem",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("codigo_origem", ""), _negated=True),
                        name="ck_depara_conta_codigo_origem_nao_vazio",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="importacaolancamentos",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "descartada"), _negated=True),
                fields=("empresa", "sha256"),
                name="importacao_lancamentos_sha_unico_por_empresa",
            ),
        ),
        migrations.AddConstraint(
            model_name="importacaolancamentos",
            constraint=models.CheckConstraint(
                condition=models.Q(("estado__in", ["em_conferencia", "efetivada", "descartada"])),
                name="ck_importacao_lancamentos_estado_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="importacaolancamentos",
            constraint=models.CheckConstraint(
                condition=models.Q(("formato__in", ["ecd", "proprio", "excel", "referencia"])),
                name="ck_importacao_lancamentos_formato_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="lancamentoimportado",
            constraint=models.UniqueConstraint(
                fields=("importacao", "numero_origem"),
                name="lancamento_importado_numero_unico_por_importacao",
            ),
        ),
        migrations.RunPython(_criar_gatilhos, _remover_gatilhos),
    ]
