# Generated by Django 6.1.2 on 2026-10-08 17:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidade", "0024_dl077_importacao_lancamentos"),
    ]

    operations = [
        migrations.AddField(
            model_name="importacaolancamentos",
            name="aceite_do_arquivo",
            field=models.BooleanField(
                default=False, verbose_name="aviso do arquivo aceito"
            ),
        ),
        migrations.AddField(
            model_name="importacaolancamentos",
            name="exige_aceite_do_arquivo",
            field=models.BooleanField(
                default=False, verbose_name="exige aceite do arquivo"
            ),
        ),
        migrations.AddField(
            model_name="importacaolancamentos",
            name="quantidade_erros_do_arquivo",
            field=models.PositiveIntegerField(
                default=0, verbose_name="erros do arquivo (total)"
            ),
        ),
        migrations.AddField(
            model_name="importacaolancamentos",
            name="quantidade_erros_do_arquivo_inteiro",
            field=models.PositiveIntegerField(
                default=0, verbose_name="erros do arquivo inteiro"
            ),
        ),
        migrations.AddField(
            model_name="importacaolancamentos",
            name="quantidade_ocorrencias_do_arquivo",
            field=models.PositiveIntegerField(
                default=0, verbose_name="ocorrências do arquivo (total)"
            ),
        ),
        migrations.AddField(
            model_name="importacaolancamentos",
            name="soma_creditos_efetivados",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=18,
                verbose_name="soma dos créditos efetivados",
            ),
        ),
        migrations.AddField(
            model_name="importacaolancamentos",
            name="soma_debitos_efetivados",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=18,
                verbose_name="soma dos débitos efetivados",
            ),
        ),
    ]
