# Generated by Django 6.1.1 on 2026-09-26 21:19

import apps.empresas.fields
import apps.empresas.validators
import apps.livro_caixa.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Editado à mão (rodada 1 de auditoria): o `makemigrations`
        # apontaria para a migração MAIS RECENTE de `empresas` no momento
        # da geração ("0014_dl046_caepf") — mas este app só depende de
        # `Empresa` existir como MODELO (para o `ForeignKey`), não de
        # nenhum campo específico dela (`caepf` inclusive). Depender de
        # "0001_initial" (onde `Empresa` nasce) em vez da migração mais
        # recente evita que testes que revertem `empresas` para uma
        # migração ANTERIOR a "0014" (ex.: `test_dl038_migracao.py`,
        # `test_dl076_b8_modo_escrituracao_constraint.py`) precisem
        # desaplicar — e não conseguem reaplicar sozinhos, porque só
        # migram de volta para o líder de `empresas`, nunca para o de
        # `livro_caixa` — as duas tabelas deste app, quebrando qualquer
        # teste deste app rodado DEPOIS, na mesma sessão da suíte
        # completa (medido: `UndefinedTable` em `test_a2_corrida_...`).
        ("empresas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContaLivroCaixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, verbose_name="código")),
                ("nome", models.CharField(max_length=200, verbose_name="nome")),
                (
                    "natureza",
                    models.CharField(
                        choices=[("receita", "Receita"), ("despesa", "Despesa")],
                        max_length=10,
                        verbose_name="natureza",
                    ),
                ),
                (
                    "codigo_carne_leao",
                    models.CharField(
                        help_text="Rendimento (R01.xxx.xxx) para conta de receita; pagamento (P10/P11/P20 + dígitos) para conta de despesa (HI-30).",
                        max_length=30,
                        verbose_name="código do Carnê-Leão Web",
                    ),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="ativa")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contas_livro_caixa",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "conta do livro-caixa",
                "verbose_name_plural": "contas do livro-caixa",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="LancamentoCaixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        validators=[
                            apps.livro_caixa.validators.validar_data_de_lancamento_caixa_do_modelo
                        ],
                        verbose_name="data",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="valor",
                    ),
                ),
                (
                    "historico",
                    models.CharField(max_length=300, verbose_name="histórico"),
                ),
                (
                    "documento_origem",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="documento de origem",
                    ),
                ),
                (
                    "recebido_de",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PF", "Pessoa física"),
                            ("PJ", "Pessoa jurídica"),
                            ("EX", "Exterior"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="recebido de",
                    ),
                ),
                (
                    "cpf_titular_pagamento",
                    apps.empresas.fields.CPFModelField(
                        blank=True,
                        default="",
                        max_length=11,
                        validators=[apps.empresas.validators.validar_cpf],
                        verbose_name="CPF do titular do pagamento",
                    ),
                ),
                (
                    "cpf_beneficiario_servico",
                    apps.empresas.fields.CPFModelField(
                        blank=True,
                        default="",
                        max_length=11,
                        validators=[apps.empresas.validators.validar_cpf],
                        verbose_name="CPF do beneficiário do serviço",
                    ),
                ),
                (
                    "cnpj_pagador",
                    apps.empresas.fields.CNPJModelField(
                        blank=True,
                        default="",
                        max_length=14,
                        validators=[apps.empresas.validators.validar_cnpj],
                        verbose_name="CNPJ do pagador",
                    ),
                ),
                (
                    "chave_idempotencia",
                    models.CharField(
                        blank=True,
                        help_text="Cabeçalho Idempotency-Key enviado pelo cliente. Repetir o POST com a mesma chave, na mesma empresa, devolve o lançamento já criado em vez de duplicá-lo.",
                        max_length=255,
                        null=True,
                        verbose_name="chave de idempotência",
                    ),
                ),
                (
                    "chave_idempotencia_fingerprint",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="impressão digital da chave de idempotência",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "conta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lancamentos",
                        to="livro_caixa.contalivrocaixa",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lancamentos_caixa",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "estorno_de",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estornos",
                        to="livro_caixa.lancamentocaixa",
                    ),
                ),
            ],
            options={
                "verbose_name": "lançamento de caixa",
                "verbose_name_plural": "lançamentos de caixa",
                "ordering": ["-data", "-criado_em"],
            },
        ),
        migrations.AddConstraint(
            model_name="contalivrocaixa",
            constraint=models.UniqueConstraint(
                fields=("empresa", "codigo"),
                name="conta_livro_caixa_codigo_unico_por_empresa",
            ),
        ),
        migrations.AddConstraint(
            model_name="contalivrocaixa",
            constraint=models.CheckConstraint(
                condition=models.Q(("natureza__in", ["receita", "despesa"])),
                name="conta_livro_caixa_natureza_valida",
            ),
        ),
        migrations.AddConstraint(
            model_name="lancamentocaixa",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor__gt", 0)),
                name="lancamento_caixa_valor_positivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="lancamentocaixa",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estorno_de__isnull", False)),
                fields=("estorno_de",),
                name="lancamento_caixa_estorno_de_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="lancamentocaixa",
            constraint=models.UniqueConstraint(
                condition=models.Q(("chave_idempotencia__isnull", False)),
                fields=("empresa", "chave_idempotencia"),
                name="lancamento_caixa_chave_idempotencia_unica_por_empresa",
            ),
        ),
    ]
