# Generated by Django 6.1.1 on 2026-09-26 23:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livro_caixa", "0001_inicial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamentocaixa",
            name="cpf_beneficiario_nao_informado",
            field=models.BooleanField(
                default=False, verbose_name="CPF do beneficiário não informado"
            ),
        ),
        migrations.AlterField(
            model_name="contalivrocaixa",
            name="codigo",
            field=models.CharField(
                max_length=20,
                validators=[django.core.validators.ProhibitNullCharactersValidator()],
                verbose_name="código",
            ),
        ),
        migrations.AlterField(
            model_name="contalivrocaixa",
            name="nome",
            field=models.CharField(
                max_length=200,
                validators=[django.core.validators.ProhibitNullCharactersValidator()],
                verbose_name="nome",
            ),
        ),
        migrations.AlterField(
            model_name="lancamentocaixa",
            name="chave_idempotencia",
            field=models.CharField(
                blank=True,
                help_text="Cabeçalho Idempotency-Key enviado pelo cliente. Repetir o POST com a mesma chave, na mesma empresa, devolve o lançamento já criado em vez de duplicá-lo.",
                max_length=255,
                null=True,
                validators=[django.core.validators.ProhibitNullCharactersValidator()],
                verbose_name="chave de idempotência",
            ),
        ),
        migrations.AlterField(
            model_name="lancamentocaixa",
            name="documento_origem",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                validators=[django.core.validators.ProhibitNullCharactersValidator()],
                verbose_name="documento de origem",
            ),
        ),
        migrations.AlterField(
            model_name="lancamentocaixa",
            name="historico",
            field=models.CharField(
                max_length=300,
                validators=[django.core.validators.ProhibitNullCharactersValidator()],
                verbose_name="histórico",
            ),
        ),
    ]
