# Generated by Django 6.1.1 on 2026-09-27 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        # Editado à mão, mesmo motivo/mesma correção de `0001_inicial.py`
        # (rodada 1 de auditoria da fatia 1): `DependentesCarneLeaoCliente`
        # só depende de `Empresa` existir como MODELO, não de nenhum campo
        # específico da migração mais recente de `empresas` no momento da
        # geração ("0014_dl046_caepf") — apontar para "0001_initial" evita
        # a mesma fragilidade de reversão já documentada ali.
        ("empresas", "0001_initial"),
        ("livro_caixa", "0002_rodada1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VigenciaTabelaProgressivaCarneLeao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vigencia_inicio",
                    models.DateField(verbose_name="vigência (início)"),
                ),
                ("fonte", models.TextField(verbose_name="fonte normativa")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
            ],
            options={
                "verbose_name": "vigência da tabela progressiva do carnê-leão",
                "verbose_name_plural": "vigências da tabela progressiva do carnê-leão",
                "ordering": ["-vigencia_inicio"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vigencia_inicio",),
                        name="vigencia_tabela_carne_leao_inicio_unico",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VigenciaDependenteCarneLeao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vigencia_inicio",
                    models.DateField(verbose_name="vigência (início)"),
                ),
                ("fonte", models.TextField(verbose_name="fonte normativa")),
                (
                    "valor_por_dependente",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="valor por dependente",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
            ],
            options={
                "verbose_name": "vigência do valor por dependente do carnê-leão",
                "verbose_name_plural": "vigências do valor por dependente do carnê-leão",
                "ordering": ["-vigencia_inicio"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vigencia_inicio",),
                        name="vigencia_dependente_carne_leao_inicio_unico",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("valor_por_dependente__gte", 0)),
                        name="dependente_carne_leao_valor_nao_negativo",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VigenciaReducaoCarneLeao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vigencia_inicio",
                    models.DateField(verbose_name="vigência (início)"),
                ),
                ("fonte", models.TextField(verbose_name="fonte normativa")),
                (
                    "limite_faixa_plena",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="limite da faixa de redução plena",
                    ),
                ),
                (
                    "reducao_maxima",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="redução máxima (faixa plena)",
                    ),
                ),
                (
                    "constante_formula",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="constante da fórmula linear",
                    ),
                ),
                (
                    "coeficiente",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=10,
                        verbose_name="coeficiente da fórmula linear",
                    ),
                ),
                (
                    "limite_superior",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="limite superior (fim da redução)",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
            ],
            options={
                "verbose_name": "vigência da redução do carnê-leão (Lei 15.270/2025)",
                "verbose_name_plural": "vigências da redução do carnê-leão (Lei 15.270/2025)",
                "ordering": ["-vigencia_inicio"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vigencia_inicio",),
                        name="vigencia_reducao_carne_leao_inicio_unico",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("limite_faixa_plena__gte", 0),
                            ("reducao_maxima__gte", 0),
                            ("limite_superior__gte", 0),
                        ),
                        name="reducao_carne_leao_valores_nao_negativos",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DependentesCarneLeaoCliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveSmallIntegerField(verbose_name="quantidade de dependentes"),
                ),
                (
                    "competencia_inicio",
                    models.DateField(verbose_name="vigente a partir de (mês)"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dependentes_carne_leao",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "quantidade de dependentes do carnê-leão",
                "verbose_name_plural": "quantidades de dependentes do carnê-leão",
                "ordering": ["empresa", "-competencia_inicio"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "competencia_inicio"),
                        name="dependentes_carne_leao_competencia_unica_por_empresa",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FaixaTabelaProgressivaCarneLeao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.PositiveSmallIntegerField(verbose_name="ordem")),
                (
                    "limite_inferior",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="limite inferior"
                    ),
                ),
                (
                    "limite_superior",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="limite superior",
                    ),
                ),
                (
                    "aliquota",
                    models.DecimalField(
                        decimal_places=4, max_digits=6, verbose_name="alíquota (fração)"
                    ),
                ),
                (
                    "parcela_a_deduzir",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="parcela a deduzir",
                    ),
                ),
                (
                    "vigencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faixas",
                        to="livro_caixa.vigenciatabelaprogressivacarneleao",
                    ),
                ),
            ],
            options={
                "verbose_name": "faixa da tabela progressiva do carnê-leão",
                "verbose_name_plural": "faixas da tabela progressiva do carnê-leão",
                "ordering": ["vigencia", "ordem"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vigencia", "ordem"),
                        name="faixa_carne_leao_ordem_unica_por_vigencia",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ordem__gte", 1)),
                        name="faixa_carne_leao_ordem_positiva",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("aliquota__gte", 0), ("aliquota__lte", 1)),
                        name="faixa_carne_leao_aliquota_valida",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("limite_inferior__gte", 0)),
                        name="faixa_carne_leao_limite_inferior_nao_negativo",
                    ),
                ],
            },
        ),
    ]
