# Generated by Django 6.1.1 on 2026-09-27 18:50
#
# DL-046, fatia 3 (RC-127): campos aditivos para os arquivos de importação
# do Carnê-Leão Web, sem alterar dado existente — sobreposição do código de
# ocupação na conta (HI-34), IRRF retido e competência/multa/juros do
# pagamento de previdência oficial (P20.01.00001). Fonte: instruções dos
# modelos de importação (Receita Federal, 2025) e página "Formato do
# arquivo de Escrituração" (consultada em 2026-09-27) — ver o plano DL-046,
# seção da fatia 3.
#
# ⚠️ Dependência de `empresas` FIXADA À MÃO em `0001_initial` (nunca
# `0015_dl046_fatia3_codigo_ocupacao`, que o `makemigrations` propôs por
# padrão — a migração MAIS RECENTE de `empresas` no momento da geração).
# Este app só precisa que o MODELO `Empresa` exista (para o `ForeignKey`
# de `ContaLivroCaixa`/`LancamentoCaixa`, herdado das migrações
# anteriores) — o import de `apps.empresas.validators.
# validar_codigo_ocupacao`, abaixo, é um import PYTHON (o validador do
# campo), não uma dependência de MIGRAÇÃO (não exige nenhum campo
# específico de `Empresa` já criado). Mesmo achado colateral já corrigido
# na fatia 1 (`livro_caixa.0001_inicial` → `empresas.0001_initial`, ver o
# comentário da migração 0001): deixar a dependência automática faria
# `MigrationExecutor.migrate()` desaplicar esta migração (e as colunas
# dela) sempre que um teste de reversão de `empresas` (ex.:
# `test_dl038_migracao.py`) migrar aquele app para trás de `0015` —
# mesmo sem qualquer relação real de dado entre as duas mudanças.
import apps.empresas.validators
import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("livro_caixa", "0007_correcao_reconferencia_mensagem_retificar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contalivrocaixa",
            name="codigo_ocupacao",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Opcional — sobrepõe o código de ocupação do cadastro da empresa só para esta conta (HI-34). Só em conta de rendimento de trabalho não assalariado ou notarial (neste último, sempre 117).",
                max_length=3,
                validators=[apps.empresas.validators.validar_codigo_ocupacao],
                verbose_name="código de ocupação (Carnê-Leão Web) — sobrepõe o do cadastro",
            ),
        ),
        migrations.AddField(
            model_name="lancamentocaixa",
            name="competencia_previdencia",
            field=models.DateField(
                blank=True,
                help_text="Obrigatória só no pagamento de previdência oficial (P20.01.00001) — sempre o primeiro dia do mês de competência.",
                null=True,
                verbose_name="competência da previdência oficial (mês)",
            ),
        ),
        migrations.AddField(
            model_name="lancamentocaixa",
            name="juros_previdencia",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=18,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="valor dos juros (previdência oficial)",
            ),
        ),
        migrations.AddField(
            model_name="lancamentocaixa",
            name="multa_previdencia",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=18,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="valor da multa (previdência oficial)",
            ),
        ),
        migrations.AddField(
            model_name="lancamentocaixa",
            name="valor_irrf",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Opcional — só em rendimento recebido de pessoa jurídica (PJ). O indicador S/N do arquivo de importação é derivado deste valor (S se maior que zero, N caso contrário).",
                max_digits=18,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="valor de IRRF retido",
            ),
        ),
        migrations.AddConstraint(
            model_name="contalivrocaixa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("codigo_ocupacao", ""),
                    ("codigo_ocupacao__regex", "^[0-9]{3}$"),
                    _connector="OR",
                ),
                name="conta_livro_caixa_codigo_ocupacao_formato_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="lancamentocaixa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valor_irrf__isnull", True),
                    ("valor_irrf__gte", 0),
                    _connector="OR",
                ),
                name="lancamento_caixa_valor_irrf_nao_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="lancamentocaixa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("multa_previdencia__isnull", True),
                    ("multa_previdencia__gte", 0),
                    _connector="OR",
                ),
                name="lancamento_caixa_multa_previdencia_nao_negativa",
            ),
        ),
        migrations.AddConstraint(
            model_name="lancamentocaixa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("juros_previdencia__isnull", True),
                    ("juros_previdencia__gte", 0),
                    _connector="OR",
                ),
                name="lancamento_caixa_juros_previdencia_nao_negativa",
            ),
        ),
        migrations.AddConstraint(
            model_name="lancamentocaixa",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("competencia_previdencia__isnull", True),
                    ("competencia_previdencia__day", 1),
                    _connector="OR",
                ),
                name="lancamento_caixa_competencia_previdencia_dia_1",
            ),
        ),
    ]
