# Generated by Django 6.1.1 on 2026-09-30 20:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0015_dl046_fatia3_codigo_ocupacao"),
        ("livro_caixa", "0009_dl052_autoria_protegida"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FechamentoMesCaixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField(verbose_name="ano")),
                ("mes", models.IntegerField(verbose_name="mês")),
                (
                    "estado",
                    models.CharField(
                        choices=[("aberto", "Aberto"), ("encerrado", "Encerrado")],
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                ("fechado_em", models.DateTimeField(verbose_name="fechado em")),
                (
                    "reaberto_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reaberto em"
                    ),
                ),
                (
                    "motivo_reabertura",
                    models.TextField(
                        blank=True,
                        default="",
                        validators=[
                            django.core.validators.ProhibitNullCharactersValidator()
                        ],
                        verbose_name="motivo da reabertura",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fechamentos_mes_caixa",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "fechado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="fechado por",
                    ),
                ),
                (
                    "reaberto_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reaberto por",
                    ),
                ),
            ],
            options={
                "verbose_name": "fechamento de mês do livro-caixa",
                "verbose_name_plural": "fechamentos de mês do livro-caixa",
                "ordering": ["empresa", "-ano", "-mes"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "ano", "mes"),
                        name="fechamento_mes_caixa_unico_por_empresa_ano_mes",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("mes__gte", 1), ("mes__lte", 12)),
                        name="fechamento_mes_caixa_mes_entre_1_e_12",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ano__gte", 1970), ("ano__lte", 2999)),
                        name="fechamento_mes_caixa_ano_entre_1970_e_2999",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("estado__in", ["aberto", "encerrado"])),
                        name="fechamento_mes_caixa_estado_valido",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("reaberto_em__isnull", True),
                                ("reaberto_por__isnull", True),
                                ("motivo_reabertura", ""),
                            ),
                            models.Q(
                                ("reaberto_em__isnull", False),
                                ("reaberto_por__isnull", False),
                                models.Q(("motivo_reabertura", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="fechamento_mes_caixa_reabertura_completa",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("estado", "encerrado"),
                            ("reaberto_em__isnull", False),
                            _connector="OR",
                        ),
                        name="fechamento_mes_caixa_aberto_exige_reabertura",
                    ),
                ],
            },
        ),
    ]
