# Generated by Django 6.1.1 on 2026-09-11 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100, verbose_name='ação')),
                ('objeto_tipo', models.CharField(blank=True, max_length=100, verbose_name='tipo do objeto')),
                ('objeto_id', models.CharField(blank=True, max_length=50, verbose_name='ID do objeto')),
                ('detalhes', models.JSONField(blank=True, default=dict, verbose_name='detalhes')),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('escritorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to='tenancy.escritorio', verbose_name='escritório')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-criado_em'],
            },
        ),
    ]
