# Generated by Django 6.1.1 on 2026-09-16 19:40

import apps.auditoria.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        ('tenancy', '0002_dl018_convite_escritorio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='escritorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=apps.auditoria.models._set_null_preservando_trilha, related_name='registros_auditoria', to='tenancy.escritorio', verbose_name='escritório'),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=apps.auditoria.models._set_null_preservando_trilha, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
